### ISSUE TITLE
Sunshine don't start and throwing an error with svchost.exe_TermService

### ISSUE THREAD

**Issue by Neomac** [DuoStream/Duo#100]
Following a Windows update, I had the issue https://github.com/DuoStream/Duo/issues/98#. 

After solving it by updating the RPDWrap.ini manually and make it read only, I now have the same issue than @namquang93 (https://github.com/DuoStream/Duo/issues/98#issuecomment-2050153755) with a "Failed to apply the display driver patch for XXXXX"
In addition to this error, I have another one in event log : 
```
  AppName svchost.exe_TermService 
  AppVersion 10.0.22621.1 
  AppTimeStamp 6dc5c2a5 
  ModuleName rdpwrap.dll 
  ModuleVersion 1.4.3.0 
  ModuleTimeStamp 661579f8 
  ExceptionCode c0000005 
  FaultingOffset 00000000000027aa 
  ProcessId 0x3c74 
  ProcessCreationTime 0x1da8d1d165f7e25 
  AppPath C:\WINDOWS\System32\svchost.exe 
  ModulePath c:\program files\duo\rdpwrap.dll 
  IntegratorReportId e25a711e-cd6c-41f4-9f27-74e961ce5aed 
  PackageFullName  
  PackageRelativeAppId  
```

I can access the duo manager page, but the sunshine server is not launching. The error is looping every 2 minutes in the event logger.

Don't hesitate to tell if you need more infos.

**Comment by niallobr** [comment]
Same, followed by
`Failed to apply the display driver patch for PC`

**Comment by loyejaotdiqr47123** [comment]
@Black-Seraph There is a slight problem with rdpwrap.dll right now, do you know how to fix it?
[https://github.com/loyejaotdiqr47123/rdpwrap/tree/master/src-x86-x64-Fusix](https://github.com/loyejaotdiqr47123/rdpwrap/tree/master/src-x86-x64-Fusix)

**Comment by Neomac** [comment]
Found the fix for this issue, the problem was that the RdpWrap.ini **ABSOLUTLY** need an empty new line at the end of the file to work (https://github.com/stascorp/rdpwrap/issues/1332#issuecomment-785119954).

Added it and made it read only did the trick for now :).

**Comment by loyejaotdiqr47123** [comment]
> 找到了此问题的修复程序，问题是RdpWrap.ini**绝对**需要在文件末尾使用一个空的换行符才能工作（[stascorp/rdpwrap#1332（注释）](https://github.com/stascorp/rdpwrap/issues/1332#issuecomment-785119954)）。
> 
> 添加它并使其只读取，现在:)。
It will be unpacked in a new version of rdpwrap
