### ISSUE TITLE
The local RdpWrap.ini doesn't contain patches for termsrv.dll version 10.0.22621.3527, attempting to pull update from GitHub

### ISSUE THREAD

**Issue by mcrstudio** [DuoStream/Duo#107]
I am trying to run the latest Patreon build and I have that error in the Event Log.

The following error is also logged:
The GitHub-hosted RdpWrap.ini doesn't support termsrv.dll version 10.0.22621.3527 yet, checking again in 30 minutes

**Comment by Black-Seraph** [comment]
RdpWrap patches gets pulled in after they are verified on a local test rig, which makes all RdpWrap.ini related issues temporary in nature as the upstream RdpWrap.ini will get updated with suitable patches eventually.
