### ISSUE TITLE
Any way to determine if current instance is virtual (for startup scripts)?

### ISSUE THREAD

**Issue by ersan** [DuoStream/Duo#108]
I'm using the same user account for all of my Duo instances as well as the host (I know this isn't advised, but managing game saves across multiple users seems like an even bigger nightmare), and there are a lot of startup items I only want to run on the host PC but not on each instance.

Is there any way to determine in a script/batch file whether or not the current instance is virtual vs. native?  I'm coming from ASTER which [has this feature](https://www.dokwiki.ibik.ru/en/v2/core/faq/faq_terminals#determination_of_workplaces_number), but I don't see a way to do it with Duo

**Comment by StijnWolf** [comment]
This isn't built-in afaik but you could just add global commands to your Duo sunshine instance which does something so you can tell the difference. I'd set an environment variable or something like that to keep track of your instance being virtual or not.

I'm on my phone a.t.m. so I can't provide proper code, but in theory it should work by letting your Duo sunshine instance set an environment variable to indicate it's virtual. Then you'd use said environment variable to check if your instance is virtual or not wherever you need to check that. You could also create and remove a file or something, but an environment variable seems more suitable to me.

**Comment by samkitty** [comment]
Yes, you can use the variable %SESSIONNAME% in a batch file in startup folder to determine whether you're in **Console** (desktop) or **RDP-TCP** (a remote session), then only start your programs if you're on host.

`@echo off`

`IF %SESSIONNAME% == Console ( REM host session, list paths to programs here prefaced by "start") ELSE ( REM Duo session, not executing programs. )`

**Comment by Black-Seraph** [comment]
There's many ways to tell, especially if you're willing to make use of rundll & the WTS API.

You can check for SW_REMOTESESSION for example.

The easiest way is checking the session name as mentioned by @samkitty.
