### ISSUE TITLE
Failed to apply the display driver patch for ...

### ISSUE THREAD

**Issue by ersan** [DuoStream/Duo#110]
When running more than 3 or 4 instances, several of them will fail to come online.  It isn't consistent which instances succeed and which fail.  Sometimes only 3 will start up, sometimes 5.

These errors appear in the event log over and over again, the instances that fail to start up have different names:

```
Failed to apply the display driver patch for Remote.
Failed to capture the display adapter (forcing a driver restart)
```

**Comment by j-scrizz** [comment]
Yeah I'm having this issue also. Any updates?
