### ISSUE TITLE
Please use Releases feature so we can watch for updates

### ISSUE THREAD

**Issue by slrgt** [DuoStream/Duo#113]
Please use the Releases feature on github so we can use github to "watch" for updates and get notifications when updates are released.

Thanks for the amazing project!

**Comment by Black-Seraph** [comment]
Will populate the repository with tags & releases sometime soon.

A little stretched thin at the moment sadly, busy month and little time to spend on projects in general.

**Comment by Black-Seraph** [comment]
All done.
