### ISSUE TITLE
Using server devices on remote session

### ISSUE THREAD

**Issue by Manuel06p** [DuoStream/Duo#115]
Hi, I recently tried to use VirtualHere in order to share my Usb Bluetooth Adapter to my pc and being able to use my Bluetooth controllers, that does not work with android, when I stream my games. The Usb Adapter is recognized by the computer as a directly connected device, and it works perfectly when I use it in a normal session. However, when I tried to use my controller with the remote session set up with duo, I could not access the controller anymore. I think that the problem might be the fact that the computer does not share local resources with the remote session (since, for instance, local mouse and keyboard are not available on the remote session). 
Is there any way to redirect some devices to a remote session?

**Comment by Black-Seraph** [comment]
Duo jails physical devices into the console session.

This is by design and the only sane way I've found to ensure devices don't start bleeding all over different sessions.

If you are technically inclined and know of a better way to deal with this feel free to let me know.

**Comment by chrispable** [comment]
I actually have the opposite problem.

A full normal interactive session playing a game with an Xbox one dongle and a connected controller.

A second connection via moonlight connects, the inputs from the primary profile input are passed through with this game controller. From what I read this should not be the case and should be handled already from the 2 different means of attempting to jail input. This was already connected for hours prior to moonlight connecting so the inputs should have been jailed before sunshine even started.
