### ISSUE TITLE
RdpWrap.ini doesn't support termsrv.dll yet

### ISSUE THREAD

**Issue by thetommah** [DuoStream/Duo#118]
Has been working perfectly for a few weeks until my windows updated this morning and ever since Duo does nothing after click the Play/Start Service button.  Everything goes grey but can't connect to the server or the Web UI, appears Sunshine never actually starts.  Checked the Event Log and I see Event:

`The GitHub-hosted RdpWrap.ini doesn't support termsrv.dll version 10.0.22621.3593 yet, checking again in 30 minutes`

**Comment by appledoc1** [comment]
Ran into this as well. I had to uninstall the latest windows security update that installed today to get Duo running again.

**Comment by thetommah** [comment]
Can confirm uninstalling latest security update does work.  I'd imagine this isn't a long term solution but certainly helps for now.

**Comment by Natepoleon** [comment]
Yeah, it would be great to know if this will be fixed.  I can't get it to work at al.

**Comment by thetommah** [comment]
> Yeah, it would be great to know if this will be fixed. I can't get it to work at al.

Well if it worked previously uninstalling the latest security update should make it work again

**Comment by Natepoleon** [comment]
Unfortunately, not an option for me as I also use this PC for work and am required to install security updates. Also restricting security updates is not a long-term sustainable solution to using a program.

**Comment by Natepoleonic** [comment]
Update: Waited a bit and everything is working properly with latest windows update!

**Comment by Black-Seraph** [comment]
Closing the issue as 1.4.6+ no longer needs RdpWrap.ini updates.
