### ISSUE TITLE
Windows security update keeps bricking Duo

### ISSUE THREAD

**Issue by NilouArmpits** [DuoStream/Duo#121]
Specifically kb5037771, I have uninstalled that update multiple times already but it keeps coming back and bricking duo, any fix? (Windows 11)

**Comment by Black-Seraph** [comment]
Are you sure about this?

I've got the update installed on all my machines and Duo behaves fine.
![Screenshot 2024-06-19 224504](https://github.com/DuoStream/Duo/assets/34379814/49eae867-d6b7-4b00-bd78-ea1e94529260)
