### ISSUE TITLE
Can't rotate game camera 360 degrees

### ISSUE THREAD

**Issue by SomeoneRand0m101** [DuoStream/Duo#122]
I assume this is an issue from touching the screen borders and it not rotating the camera after that
Ive also heard of problems with relative and absolute cursor movement but I'm not sure if it is related to this

I am playing No man's sky 

https://github.com/DuoStream/Duo/assets/93738971/fe8c2082-a5e0-44ea-a2fe-c845e5ee164f

**Comment by zzfuture** [comment]
Is the 'Optimize mouse for remote desktop instead of games' option in Moonlight activated? Try pressing Ctrl + Shift + M when streaming to check.

**Comment by SomeoneRand0m101** [comment]
> Is the 'Optimize mouse for remote desktop instead of games' option in Moonlight activated? Try pressing Ctrl + Shift + M when streaming to check.

Ctrl + Shift + M shortcut dosen't do anything
But in moonlight settings it says its disabled so idk

**Comment by Black-Seraph** [comment]
This looks a lot like the remote desktop mouse mode has been enabled.

**Comment by heron1** [comment]
Same issue here, optimize mouse for remote desktop is disabled in moonlight
