### ISSUE TITLE
Ransomware Reporting via Kaspersky, Bitdefender, and Virustotal

### ISSUE THREAD

**Issue by lunar-studio** [DuoStream/Duo#124]
Bitdefender has saved me on multiple occasions, although their interface is terrible. I just installed the Patreon version and it set numerous warnings off. I had difficulty adding exceptions through their various threat defenses even after disabling everything. I then uploaded the latest duo.exe file to Kaspersky and it identified it as a Trojan-Ransom.Win32.Foreign (Ransomware.)

Further, Virustotal pulled up several warnings. Interestingly, Bitdefender through VT didn't show a positive.

I can believe that the RDPWrapper and other files would likely lead to false positives, but I thought you might want to make a public statement for clarification as to why these are showing up as harmful.
![virus-total-scan](https://github.com/DuoStream/Duo/assets/58184329/9fef6562-b772-4776-9a8c-199f7004cf4a)

**Comment by Black-Seraph** [comment]
The AV false positives associated with Duo and its components have been well documented in its Wiki alongside detailed descriptions as to what I assume might be causing them in the first place.

See the [known issues page](https://github.com/DuoStream/Duo/wiki/Known-Issues#antivirus-false-positives) of the Wiki.
