### ISSUE TITLE
Screen black upon starting `Desktop` app from Moonlight

### ISSUE THREAD

**Issue by corban123** [DuoStream/Duo#126]
Have Duo setup where the instance runs on a secondary user from the one that is currently logged in. I start the stream via the Desktop app in moonlight, but despite successfully connecting, there is just a black screen, nothing else. No logs in Event Viewer that mentions this failure, nor anything in Sunshine.

**Comment by Black-Seraph** [comment]
Have you tried moving the mouse a bit after connecting?

Depending on your instance's dwm.exe lazy refresh state it can take up to a minute of 0-activity for the first frame to come in from the swapchain.

One can accelerate this down to a few seconds tops by moving the mouse, which gives dwm.exe a kick in the butt and activates the swapchain.

**Comment by corban123** [comment]
Have attempted to move my mouse and tap around, no dice.

**Comment by xsmolasses** [comment]
Were Moonlight not sending UDP to destination Sunshine:MainPort+9, it'll complete the handshake regardless and you'd see a black screen for several seconds before being kicked.

Moreover, if Moonlight were not sending as above, means Windows' stateful packet inspection won't permit datagrams sent back from Sunshine to Moonlight's ephemeral source port.

If we suppose Moonlight's periodic datagrams are sent unconditionally and getting through but Sunshine's return UDP is not, Sunshine is unaware and nonplussed about it? Shrugs.

Troubleshoot: Delete PC in Moonlight, try a loopback address - this could be your DHCP assigned IP (Windows' routing finds the shortest path), or localhost, 127.0.0.1:GivenPort

^ This is like Looking Glass or something wicked! Shame we can't bypass the compression-decompression stages. Do I understand right, Version 1.4.5 supports running in a Docker?

Y'know opening the Duo Manager, duoconfig.exe connects to Microsoft servers:80 - ya downloading symbols or somethin'? (duo.exe first run hit GitHub:443 and was to be expected.)

query[A] ctldl.windowsupdate.com
query[A] msedge.b.tlu.dl.delivery.mp.microsoft.com

**Comment by appledoc1** [comment]
Had the same issue lately. It was just the oled Deck wifi chip in low power mode bug. Had to toggle wifi off and on to fix it until the next time

**Comment by RStanbouly** [comment]
To add - I've now attempted to add my instance to both my steamdeck and my nvidia shield, however both sessions result in a black screen (and interestingly enough, my logs indicate that it is unable to get audio?

```
[2024:06:23:20:53:09]: Warning: Couldn't set [virtual-Stereo{3.0.0.00000006}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}] to role [0]: 0x80004002
[2024:06:23:20:53:09]: Warning: Couldn't set [virtual-Stereo{3.0.0.00000006}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}] to role [1]: 0x80004002
[2024:06:23:20:53:09]: Warning: Couldn't set [virtual-Stereo{3.0.0.00000006}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}] to role [2]: 0x80004002
[2024:06:23:20:53:09]: Error: Unable to initialize audio capture. The stream will not have audio.
```

I attempted updating Sunshine to the latest version (Seems Duo is pointing at .22), would that cause issues?

**Comment by Black-Seraph** [comment]
> To add - I've now attempted to add my instance to both my steamdeck and my nvidia shield, however both sessions result in a black screen (and interestingly enough, my logs indicate that it is unable to get audio?
> 
> ```
> [2024:06:23:20:53:09]: Warning: Couldn't set [virtual-Stereo{3.0.0.00000006}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}] to role [0]: 0x80004002
> [2024:06:23:20:53:09]: Warning: Couldn't set [virtual-Stereo{3.0.0.00000006}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}] to role [1]: 0x80004002
> [2024:06:23:20:53:09]: Warning: Couldn't set [virtual-Stereo{3.0.0.00000006}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}] to role [2]: 0x80004002
> [2024:06:23:20:53:09]: Error: Unable to initialize audio capture. The stream will not have audio.
> ```
> 
> I attempted updating Sunshine to the latest version (Seems Duo is pointing at .22), but did not seem to solve my issue. Would that cause issues?

The included sunshine build is tailor-made for use with Duo.

You can't substitute it with a regular sunshine build and expect things to work.

**Comment by corban123** [comment]
Upgrading to 1.4.6, and it seems I'm sadly back to receiving `Failed to apply the display driver patch for Duo`. Attempting to downgrade back to 1.4.5 did not seem to solve the issue.

**Comment by Black-Seraph** [comment]
@corban123 Please follow [the instructions](https://github.com/DuoStream/Duo/issues/128#issuecomment-2196713513) posted in #128.

**Comment by corban123** [comment]
Bad news @Black-Seraph , same issue as what Mario mentioned in there. 
[EventsForDuo.zip](https://github.com/user-attachments/files/16037490/EventsForDuo.zip)
No events marked for DuoIdd, yet I have all the files mentioned in your post [here](https://github.com/DuoStream/Duo/issues/128#issuecomment-2197413389)

**Comment by Black-Seraph** [comment]
> Bad news @Black-Seraph , same issue as what Mario mentioned in there. [EventsForDuo.zip](https://github.com/user-attachments/files/16037490/EventsForDuo.zip) No events marked for DuoIdd, yet I have all the files mentioned in your post [here](https://github.com/DuoStream/Duo/issues/128#issuecomment-2197413389)

Keep following that thread.

I've posted updated instructions for Mario there that apply to your case as well.

**Comment by corban123** [comment]
@Black-Seraph doing the command as requested in the terminal has the terminal hang for a while, but no error appears. I do question whether or not I've entered the right stuff (is it either the computer's name or the instance username? Or was it something else?)

**Comment by Black-Seraph** [comment]
@corban123 Before anything else try the newly released version 1.4.7 build.

I debugged Mario's issue today and fixed it.

If your issue has the same cause then this should fix it for you too.

If not, we'll resume debugging together.

**Comment by corban123** [comment]
@Black-Seraph this is so strange. I had a few days where it was working perfectly - no black screen, everything logged in correctly, no biggie. Back to getting `Failed to attach display driver patch` again

**Comment by Black-Seraph** [comment]
> @Black-Seraph this is so strange. I had a few days where it was working perfectly - no black screen, everything logged in correctly, no biggie. Back to getting `Failed to attach display driver patch` again

On the latest version?

**Comment by Black-Seraph** [comment]
Closing this issue as your real issue is with #114.
