### ISSUE TITLE
Install: An error occurred while trying to copy a file: Out of memory

### ISSUE THREAD

**Issue by niallobr** [DuoStream/Duo#13]
I am getting this error while trying to install Duo on Windows 11 Enterprise 22H2.

![Screenshot 2023-11-04 201710](https://github.com/DuoStream/Duo/assets/204252/e1a0da9b-960c-4934-a5bb-f5f378ef9c20)

 System memory seems to be fine. If I skip, the next file shows the same error.

I uninstalled Sunshine and Hidhide before running the Duo installer. I also tried a few obvious things like a reboot and disabling Real-time protection in Windows Security.

Any help would be great and thanks for the work on the project.

**Comment by niallobr** [comment]
Seems to be solved after another doing another reboot. Only other difference was I kept Firefox closed while installing? Maybe it was hogging some memory?

**Comment by Yasito** [comment]
I have the exact same issue but it still occurs even after rebooting and without anything else open.
