### ISSUE TITLE
Controllers keep waking up monitor on host PC

### ISSUE THREAD

**Issue by ersan** [DuoStream/Duo#130]
I don't know if this is solvable - but pressing any button on any controller jailed to any instance of Duo/sunshine will wake up the monitor on the host PC

Would obviously prefer that it stay off unless the keyboard/mouse attached to it are being used, but I can't figure out how to make that happen.

**Comment by samkitty** [comment]
This has been addressed before, I provided a [workaround](https://github.com/DuoStream/Duo/issues/117#issuecomment-2114771023) but an official fix isn't currently possible.
