### ISSUE TITLE
Moonlight doesn't see the duo instance outside of network

### ISSUE THREAD

**Issue by jonginator** [DuoStream/Duo#131]
It can see the regular Sunshine server fine but not the duo created instance. 

Have UPnP enabled and also forwarded the port listed on the instance. 

On the latest Patreon version if that matters.

**Comment by Black-Seraph** [comment]
Works for me but I'll look into it.

**Comment by jonginator** [comment]
> Works for me but I'll look into it.

Did you have to do anything extra?

Like what were the steps you took to get it working?

**Comment by Black-Seraph** [comment]
@jonginator Nothing extra was needed, but my routing setup is anything but average, so that might play into this somehow.

Which is why I'm not dismissing your issue, but rather investigating it.

**Comment by Black-Seraph** [comment]
@jonginator Could you let your UPnP-enabled instance run for 10 minutes or so and then copy out and attach your instance's log file?

**Comment by warlordianx3** [comment]
I used DDNS method from the router feature, because my IP is Dynamic, IP Address keeps changing, and UPNP helps a lot. VPN also helps if your router has a built in VPN   like  WireGuard , Zaro Tier or Tailscale

**Comment by jonginator** [comment]
@Black-Seraph 

I was able to fix the problem. 

Sunshine kept disabling UPnP for some reason. Got it to stick the third time around.
