### ISSUE TITLE
 Info: Web UI: [127.0.0.1] -- not authorized

### ISSUE THREAD

**Issue by Qfrijters** [DuoStream/Duo#132]
I used to run Sunshine in a VM and never got that message. Now I run it on the host pc (the vm is off to be clear) and I get a mostly constant stream of that error. I know it's Sunshine but I don't have this when I run Sunshine and not use Duo.

Here's the complete log :)
[gaming.log](https://github.com/user-attachments/files/16115555/gaming.log)

**Comment by Black-Seraph** [comment]
You have the Manager app open.

It polls the WebUI port to determine whether the Sunshine instance is operational.

That means this is expected behavior.

I plan to change this over to the RTSP port in version 1.4.8, which will get rid of the error message as a side-effect.
