### ISSUE TITLE
UI only listens on localhost

### ISSUE THREAD

**Issue by ddscentral** [DuoStream/Duo#134]
The UI and Sunshine instances are set to only listen for local connections, making it nearly impossible to use on headless systems. Any way to enable non-localhost connections without resorting to things like single port proxies ? Maybe there's a setting in the config file ?

**Comment by ddscentral** [comment]
Never mind, Sunshine instance itself does still work over LAN. Would still be nice to have the main UI accessible too, to enable easier navigation between different Sunshine instances.

Currently test-driving the free version, if it can work reliably, will consider grabbing the paid version. All other remote softwares (stock Sunshine, Parsec, TightVNC) I've tried so far worked unreliably on my vGPU VM setup (freeze-ups, black screens, etc.) except for the built-in RDP server.

**Comment by Black-Seraph** [comment]
The UI listens on 0.0.0.0, aka. all interfaces.

Maybe your firewall is blocking external access to the port?

I regularly start and stop instance from the WebUI using my smartphone while sitting in front of my living room TV, so I know for a fact it works just fine.

**Comment by ddscentral** [comment]
Thanks for the advice. 
Yes it's likely the Windows' built-in firewall is at fault. Completely forgot to check it, I rarely host anything on Windows.
