### ISSUE TITLE
Games not compatible with remote login

### ISSUE THREAD

**Issue by EnriqueSampaio** [DuoStream/Duo#136]
Are there anything I can do about games that are not compatible with remote login?

For example, I was trying to use Duo to play PES eFootball 2021 remotely but the game gives me the error saying it is not compatible with remote login and closes. There is anything I can do to bypass that or those games are not possible to play with Duo?

Thanks in advance for the support and for developing such a great tool!

**Comment by samkitty** [comment]
You can try launching the game (or Steam itself) using CMD with the command `runas /user:[INSERT LOCAL HOST USERNAME HERE] "C:\Program Files (x86)\Steam\steam.exe"`
This will prompt you to enter the password of the local user, and then will launch Steam under the local host but it will show up on your Duo instance display. If I'm not mistaken any Steam game you launch afterwards will have no idea that you're using a remote login.

![320653207-96651ad1-1521-400f-8e98-b00e4fa9d84c](https://github.com/user-attachments/assets/b6911227-7db0-4504-bc2e-881c040c02b7)

**Comment by EnriqueSampaio** [comment]
I'm probably doing some rookie mistakes here, if you can give me any tips I'll appreciate.

I'm not sure what you are calling the "localhost user name" here, but I've tried using the username that is logged directly on my computer without sunshine, which is an MS account. Also tried a local account that is not being used at all and tried also the account that is being used on the instance authentication. Tried the last two both with my PC namespace and with "localhost/[USER NAME]". The error is the same all the time.

Everything I tried was through Moonlight, should I run the command locally on my PC? If that's the case, I don't know how it would work, since I'm using different users on my PC locally and on the moonlight connection.

Oh, and it's not a Steam game. Actually is a modded version of the PES 2021 with updated stuff, but that limitation comes from the original PES.

**Comment by warlordianx3** [comment]
It's Sunshine and Moonlight Support issues not DUO

**Comment by EnriqueSampaio** [comment]
I'm pretty sure it's DUO issue because using Sunshine/Moonlight without DUO it works.

To be fair, the problem is that DUO uses RDP to create remote desktop sessions and some games don't like remote desktops at all, I was just wondering if there was any way to trick the game into believing it is not a remote desktop, since Windows have a lot of weird bypasses that would not be a surprise lol.

**Comment by Black-Seraph** [comment]
If the game doesn't use anti-cheat then this issue can be worked around by hooking a few key functions in ntdll.dll / user32.dll.

See #139 for more details.

**Comment by Black-Seraph** [comment]
@EnriqueSampaio I don't own PES 2021, but it would go a long way if you could zip up and attach the game's .exe & .dll files so I can take a look sometime.

**Comment by Black-Seraph** [comment]
Closed for inactivity.

**Comment by jorbig** [comment]
I stumble upon the exact same issue with Pro Evolution Soccer 2013. It says "Not Compatible with Remote Login."

![Screenshot 2024-10-05 162928](https://github.com/user-attachments/assets/8a1d1539-38c5-4bdf-95db-4492519a2310)

Here is the game's .exe & .dll. I hope you can have a look at it!

[Pro Evolution Soccer 2013.zip](https://github.com/user-attachments/files/17266543/Pro.Evolution.Soccer.2013.zip)
