### ISSUE TITLE
Windows 11 LTSC

### ISSUE THREAD

**Issue by garbagescow** [DuoStream/Duo#137]
Hello, 

Has this been tested on Win 11 LTSC?  Everything seems greyed out, and if I start duo, it just stops after several seconds.

I have sunshine already running on the host, so I don't know if that would affect it.

![image](https://github.com/user-attachments/assets/11a6aa07-6b0b-4fc5-afdb-e2a8014c7e73)

![image](https://github.com/user-attachments/assets/ae2a9bde-c223-4fb7-a5db-52278c15a569)

**Comment by xsmolasses** [comment]
Click tab heading edit box. Hit enter...
'Twas a stumbling block for me also!

(And no worries running Duo alongside official Sunshine.)

**Comment by garbagescow** [comment]
> Click tab heading edit box. Hit enter... 'Twas a stumbling block for me also!
> 
> (And no worries running Duo alongside official Sunshine.)

That was the problem Works Now.  Thanks.

**Comment by yybfrank** [comment]
![1728638833570](https://github.com/user-attachments/assets/486f2c09-66e7-4737-8291-c3f6b07c3ecc)
enter ...

**Comment by xsmolasses** [comment]
> enter ... still has problem
Numbers, Letters, Underscores maybe.

**Comment by m33ts4k0z** [comment]
Just use a real word there and press enter. It should work. No need to use symbols and such.

**Comment by yybfrank** [comment]
> bers, Letters, Un
Yes, it's resolved

**Comment by yybfrank** [comment]
> > enter ... still has problem
> 
> Numbers, Letters, Underscores maybe.

That's right,it's resolved
