### ISSUE TITLE
Duo  instance issue 

### ISSUE THREAD

**Issue by Tech0612** [DuoStream/Duo#138]
Can't get an instance started. Checked event Viewer and receive these errors "The TermService wrapper couldn't be enabled" and "The local TermService version isn't supported" Any help would be appreciated. I've messaged the Dev and I'm sure he's very busy and has many people messaging him.
Ive already followed all Troubleshooting Steps I have the latest Patreon Version

**Comment by warlordianx3** [comment]
Make sure you put DUO for exemption  and running on latest  Windows

**Comment by Black-Seraph** [comment]
What @warlordianx3 said is a good first try, as the error message clearly indicates that something is actively blocking Duo from configuring the local TermService.

**Comment by Black-Seraph** [comment]
Closed for inactivity.
