### ISSUE TITLE
Duo Stream Loop

### ISSUE THREAD

**Issue by Tylersilva93** [DuoStream/Duo#140]
Set up Duo Stream, when i press the start service button, after a few minutes i get kicked out to the login screen in which i have to login manually, then when I do. it happens again shortly after. I cant connect to moonlight since i cant even get to the Web Admin page.

**Comment by Black-Seraph** [comment]
What version of Windows are you running?

**Comment by Black-Seraph** [comment]
Closed for inactivity.
