### ISSUE TITLE
Any way to Duostream into Main Remote Desktop?

### ISSUE THREAD

**Issue by lunar-studio** [DuoStream/Duo#143]
I saw your newsletter and know you’re pretty busy right now.
Is there any way to Remote Desktop via Moonlight and Duo into the main/default Windows 11 account?
I have a bunch of applications running and noticed they’re not displayed when running through Moonlight with Duo so I can’t control them. In particular, I’m running Forge (Stable Diffusion) and wanted to restart the processes remotely.

**Comment by Orski174** [comment]
Just download sunshine and set it up locally, accessing the main open user is the exact opposite what duo was designed for.

**Comment by Black-Seraph** [comment]
@lunar-studio It's pretty much the way @Orski174 said, this isn't what Duo was made for and as such goes beyond the scope of the project.

The proper way to connect into the console session is to use regular old Sunshine, which, by the way, can peacefully co-exist with Duo (sans gamepad jailing support of course).
