### ISSUE TITLE
Login to non-Duo user accounts should connect to already logged in local session

### ISSUE THREAD

**Issue by Shanayara** [DuoStream/Duo#146]
Duo exists such that a secondary user account (not my local user account) can start and stream games in the background.

However, I also sometimes want to use the "normal" remote desktop usecase: login to the currently running session on my computer, e.g. start work on my desktop PC and then going to the garden and taking my laptop with me, and continuing the work on the dekstop PC via remote desktop. However, when I do that with Duo installed, I am now logged into a completely new session of the user instead and do not have access to the previously opened programs. There's even some errors because programs which are already running in the logged in session get auto-started a second time, but cannot access the same resources (e.g. Firefox complains it's already running).

Please make it possible for us tu use Remote Desktop "normally", to have the behavior of having a single login session for every user that isn't configured in Duo, where the "multi login" is actually required. Right now I don't see any option to do so.

**Comment by samkitty** [comment]
I'd love to have this as well so I don't need to keep 2 versions of Sunshine for when I need my local account remotely. Having the 2 instances show up at once in Moonlight would be incredibly useful.

**Comment by Shanayara** [comment]
This isn't about Moonlight. The bug I describe happens when connecting to the PC with the normal "Remote Desktop" application bundled with Windows. I am not trying to connect via Moonlight/Sunshine to my actual local user account.

**Comment by samkitty** [comment]
Right, I have the same use case as you but I just use Sunshine for both, work and play. I haven't tried connecting through RDP with Duo installed, but yeah what you describe sounds messy.

**Comment by Black-Seraph** [comment]
@Shanayara This isn't possible due to the One-Account / Multiple-Logon policy being a hard requirement for Duo to function. Not having this policy enabled would run the risk of users locking themselves out of their console session if they only have a single local account which happens to also be configured in Duo, which is too great a risk for me to implement manual control of this policy in good faith.
