### ISSUE TITLE
Scaling value ignored

### ISSUE THREAD

**Issue by niallobr** [DuoStream/Duo#15]
My resolution is 3840x2160 and I’m trying to set my scaling value to 150-175 (same as the host) but it seems to be stuck at 100 when I stream using the Moonlight app. Everything is very small on the screen. I’ve tried the latest free and Patreon versions. Also tried executing RDP_CnC.exe and updating the .ini. System is running Windows 11 Enterprise 22H2, Ryzen 7 3800X, RTX 2080 Super. Any suggestions would be much appreciated please.

**Comment by Black-Seraph** [comment]
I can confirm the issue on a broken-screen spare notebook I've got laying around with a fresh Windows 11 23H2 install.

Looking at that notebook's RdpIdd.dll file in Ghidra, I found that the scale offset in the MonitorConfig structure differs there, which would explain why the scale options aren't being applied.

I will see what I can do about this.

**Comment by Black-Seraph** [comment]
[Fixed.](https://github.com/DuoStream/Duo/commit/3df0cea1a838afc84054863a25f8a7d09b5165b7)

**Comment by niallobr** [comment]
Thanks @Black-Seraph I’ll make sure to try it out over the holidays 😄

**Comment by samkitty** [comment]
@Black-Seraph I have the same issue on my Logitech G Cloud (an Android handheld), the custom scaling setting is ignored.

RdpIdd.dll version 10.0.22621.3085
Windows 11 23H2 OS Build 22631.3155

![20240225_144654](https://github.com/DuoStream/Duo/assets/57629730/ed2da5f8-21a7-4662-9ae1-a62dfe8b5032)
