### ISSUE TITLE
View instance on main PC?

### ISSUE THREAD

**Issue by Blahshead** [DuoStream/Duo#154]
Hi Black-Seraph -- in Duo, is there a way to view an ongoing instance on the main host PC? Asking because I have duo connected to my Amazon fire tv stick, but there are certain pop-ups I need to exit out of while trying to launch certain games and I don't have a mouse and keyboard connected to the TV. 

For example when I try to run CyberPunk off steam, it opens the CyberPunk launcher (which I then need to log into). The easy fix is to probably just connect my mouse and keyboard to the Fire TV stick. But I'm wondering if it's possible to instead do it all from my main PC, and then go back to my TV and play the game.

**Comment by samkitty** [comment]
Consider using [Unified Remote](https://www.unifiedremote.com/) which turns your phone into a trackpad/keyboard for your PC over wifi. There are serverless options as well (like [this](https://play.google.com/store/apps/details?id=io.appground.blek)) if you prefer to connect your phone to the Fire TV stick directly using Bluetooth.

**Comment by m33ts4k0z** [comment]
You can connect to the Sunshine instance from your PC using Moonlight? OtherwiseI noticed that RustDesk also gives you the option to choose the Sunshine instance when trying to remote control the PC.

**Comment by chrispable** [comment]
I think you would be better served with something like an auto hot key script here so you don't need to even perform these actions on boot

**Comment by Black-Seraph** [comment]
@Blahshead Install Moonlight on your host PC and pair to your instance, then you can connect to it the same way your TV does and control it as needed.

If you want to be extra special, go into the instance's Sunshine web admin panel and set the number of concurrent streams to 2, then you can control it on both your PC and your TV at the same time.
