### ISSUE TITLE
Duo not starting

### ISSUE THREAD

**Issue by n1tr0-oxide** [DuoStream/Duo#159]
i have this error whenever i start duo, i pressed the green play button but nothing works. Help

<img width="834" alt="image" src="https://github.com/user-attachments/assets/b9f98684-d201-4695-a860-176c416f929d">

**Comment by Black-Seraph** [comment]
Why would you start Duo.exe directly?

It's a Windows service, its not meant to be started like a regular application.

Closing this issue because of wrong usage.
