### ISSUE TITLE
Video Decoder Crashed

### ISSUE THREAD

**Issue by flos06** [DuoStream/Duo#160]
Not sure if this is a Duo issue, Sunshine issue or Moonlight issue.

If I set the fps target to 90 or 120fps in moonlight moonlight crashes with Video Decoder Crashed, Moonlight has crashed due to an incompatibility with this device's video decoder...

I've got the patreon version and it does this at any resolution. My tv is 120hz capable. Any Ideas what to do?

**Comment by zzfuture** [comment]
Maybe your client decoder is not capable of decode at those fps?

**Comment by xsmolasses** [comment]
Chiming in with a report that my “Chromecast with Google TV (HD)” shall error out, quitting the stream, with that same message while using “Prefer H.264” after some minutes; in my case verifiably not related to bitrate and throughput.
 
Whereas “Prefer HEVC” seems fine for hours in this regard though I've only tested 60 FPS here, sorry . . .

(An aside, performance is great, apart from occasional slow connection to PC, decrease bitrate nonsense, something else is causing brief stream halting via my 5 GHz Wi-Fi - Moonlight sorely needs a delayed presentation option, one that could be engaged on the fly, which could buffer through interruptions when you're only watching something.)

(Also for my device model, set “Video frame pacing” to “Balanced” for smooth panning & scrolling; as any other setting stutters.)

(I have not an hardware encoder to test its decode of AV1.)

**Comment by Black-Seraph** [comment]
Duo can't really do anything about decoder issues as those are entirely client-sided, not server-sided (where Duo lives).

Different client hardware has different decoding capabilities, that's just a matter of fact.

The solution to your problem is to choose client-sided settings that match up with what your client hardware can actually deal with.
