### ISSUE TITLE
Version 1.4.9 won't install on 24H2

### ISSUE THREAD

**Issue by m33ts4k0z** [DuoStream/Duo#162]
Hello.

I downloaded version 1.4.9 from Patreon and every time I start the setup, it always tries to install the dependencies. I have now restarted 6 times and the same thing happens.

The issue seems to be the version 24H2 of Windows 11 as it seems to work on 23H2 @Black-Seraph

**Comment by j-scrizz** [comment]
Yeah I am having the same issue here, also 24h2.

**Comment by m33ts4k0z** [comment]
I was running the preview version of 24H2. Installing the released version solved the problem.

**Comment by kiri11** [comment]
I have the same issue, but it's released build, not preview :(
Any idea why this could be happening?
```
Edition	Windows 11 IoT Enterprise LTSC
Version	24H2
Installed on	‎10/‎3/‎2024
OS build	26100.1882
Experience	Windows Feature Experience Pack 1000.26100.23.0
```
