### ISSUE TITLE
Duo tries to start windows user session but fails and loops with "Microsoft Remote Display Adapter" error in eventlog

### ISSUE THREAD

**Issue by aladinzz** [DuoStream/Duo#167]
Duo tries to start windows user session but fails and loops with "Microsoft Remote Display Adapter" error in eventlog.
I am not using the sandbox.
I start the service and the session in Duo Manager.
I open Taskmananer --> Users and watching the new user session appear and after a few seconds when there are about 50 processes running, the session is closing. A few seconds later the session starts again and shuts down again in an infinite loop.
I was checkin the Windows event log --> Windows Protocols --> System there are two critical errors:
1: One or more user mode drivers encountered a problem and the host process terminated. You may be temporarily unable to access the devices.
2: The device "Microsoft Remote Display Adapter" (location "(unknown)") is offline due to a user mode driver failure. The device is attempted to restart 5 times. For more information about this issue, contact the device manufacturer.

A few days ago, everything was working fine with Duo and now it´s not anymore.

System is Windows 11 23H2 up to date an the latest Nvidia grafics drivers installed.

**Comment by m33ts4k0z** [comment]
Does this issue occur with 1.4.8?

**Comment by aladinzz** [comment]
I found the problem.
The only two things i changed on my system from before with a working fine Duo was, i installed OBS Studio to record my Desktop and installed MS Teams.
So i decided to only uninstall OBS reboot and have try...
And yes, after uninstalling OBS, Duo works just fine again.
