### ISSUE TITLE
DirectX Errors on Older Games

### ISSUE THREAD

**Issue by bardemz** [DuoStream/Duo#17]
I'll stress here at the top that these errors do not occur when using Moonlight/Sunshine on their own without the assistance of Duo.

Many or most of the older games I've tried playing on Duo have thrown a DirectX error of some kind and refused to boot when using Duo, even if the game boots and runs fine locally on the machine.  Here are some of the games I've tried, and screens of their respective error messages:

[Call of Duty 2](https://imgur.com/a/lIWhkb1)
[Brothers in Arms: Road to Hill 30](https://imgur.com/a/MUClhlI)
[Half-Life 2](https://imgur.com/a/rRd7xid)
Ghost Recon (2001) and Warhammer 40K Space Marines (2011) both simply refuse to boot and do not give me an explicit error message.

I'm running on a 1080 Ti with an i9-7900X.  I will say I installed Windows 11 specifically for Duo, and went the "upgrade" path from Windows 10 instead of a clean install of Windows 11.

**Comment by Black-Seraph** [comment]
Same issue as #18, but I will leave it open for now as the games mentioned are different.

Please try the workarounds posted in #18 and report back though to verify if this is indeed the same issue or not.
