### ISSUE TITLE
Problem installing Duo

### ISSUE THREAD

**Issue by MadWizardDE** [DuoStream/Duo#170]
Hello. I found out about Duo today and now I am stoked and anxious to try out this marvelous piece of software. But when I run the installer (1.4.9.0), it's says it is installing dependecies and the Sandbox Support in particular. After some time the setup suggests to restart the computer, because some complete the install. After that I should restart the setup to continue with the installation. During the first reboot I actually saw Windows installing additional features (presumably the Windows Sandbox), but after that finished, there was just nothing. No Duo Manager can be found either. I went and started the installer a second time, but with no different outcome. It always wants to install the Sandbox Support and then to restart the computer. I didn't see Windows installing anything during the subsequent reboots.

I am on Windows 11 24H2. I have Sunshine and RDP Wrap already installed. The first shouldn't be a problem I gather. Do I have do deactivate my version of RDPWrap to continue the setup? Nevertheless I would expect at least the installation of the Duo Manager, even if it fails to work. I deactivated the Core Isolation in Windows Security and installed about additional of dozen times, with no luck. I checked the event log for errors but found none.

Did anyone had this strange issue? Can anyone help? Would really like to give support on Patreon, if this would work!

**Comment by TioBundy** [comment]
I have the same or similar problem, with the addition of not showing Duo in the windows menu.

I can't change the Windows display settings now, as well as other configuration settings.

AND AS A SERIOUS ADDITION, IT HAS DELETED MY RESTORE POINTS, so I can't restore my system before installing Duo.

I'm starting to think that this software is acting like malware, because what it's causing in my system is not at all normal.

**Comment by MadWizardDE** [comment]
@m33ts4k0z thank you very much for pointing this out. didn't realize until that moment that some parts of windows where missing, lol 🙄 but follwing the steps to uninstall the faulty packages and installing the previous version of duo fixed that issue, thankfully.
