### ISSUE TITLE
Installing 1.4.9 broke installer of Duo at all

### ISSUE THREAD

**Issue by DenSwitch** [DuoStream/Duo#171]
hi. i was trying to install duo 1.4.9 on top of patreon 1.4.8. it was installing like it should, then asked for reboot. i opened duo to check and i still got 1.4.8 installed. opening 1.4.9 installer again resulted "Out of memory" error. i uninstalled duo thinking that was the issue, and now i can't install even 1.4.8 :)
![image](https://github.com/user-attachments/assets/03128bc2-db63-4600-8fba-4cb1cd3f7504)
Windows 11 Pro 23H2

**Comment by DenSwitch** [comment]
it's not. i have like 20gb free (ram) and 80gb on ssd

**Comment by m33ts4k0z** [comment]
Do you use any antivirus? Even Windows Defender or the likes?

**Comment by m33ts4k0z** [comment]
Try following the steps from [this](https://github.com/DuoStream/Duo/issues/164#issuecomment-2398189562) link and try to install 1.4.8. Avoid 1.4.9 for the time being as it is still problematic. Wait for 1.5.0 instead.

**Comment by DenSwitch** [comment]
also, it seems that i now get broken rdp sessions as well :)

**Comment by m33ts4k0z** [comment]
You can try running it a batch file instead. A powershell script will also work.

**Comment by DenSwitch** [comment]
i got it working by installing it on another machine, copying it onto my main machine and creating Duo service. problem with installer is still relevant

**Comment by DenSwitch** [comment]
closing msi afterburner for some reason helped (#166). still, please take a look at that :)

**Comment by TioBundy** [comment]
Solved with a reinstall windows with a USB:
https://github.com/DuoStream/Duo/issues/164#issuecomment-2427867807

Option to keep files and programs if you need this.
