### ISSUE TITLE
Slow Like Motion From Frame Limiting

### ISSUE THREAD

**Issue by Orski174** [DuoStream/Duo#19]
In some games probably older games and less graphically demanding games, (in my case Terraria and Devil May Cry HD Collection) the game probably generates 60 fps but renders only 30 fps which will eventually render all of it in 2 seconds instead of one creating this slow-mo effect. 

I tried limiting FPS using Nvidia Inspector but nothing changed.

I should do more testing, for the meantime I'm putting out here for possible solutions

**Comment by Black-Seraph** [comment]
I figure you're using the freebie Github version?

If so, that means your RdpIdd driver runs at its default refresh rate of ~30Hz, which might be the cause of the problem if the game forces Vsync internally.

Patreon supporters can force the RdpIdd driver into refresh rates it doesn't support out of the box, letting you go anywhere from 30~500Hz as needed, which, most likely, will solve your problem.

I don't own either of the games you mentioned, so its difficult for me to give you a definite answer though.

**Comment by Orski174** [comment]
That is definitely it, I guess the only way to fix it is to get the patreon version.

Thanks!
