### ISSUE TITLE
no duo-manager

### ISSUE THREAD

**Issue by NeverBeLazyG** [DuoStream/Duo#190]
i installed this via duo.exe. but after a quite long installation period and a reboot nohting is shown. neither in start menu nor a desktop link. i searched the filesystem for installed files, cant find anything. what am i do wrong ? 😁

edit: now its working. its strange i installed it via rdp remotely and it didnt show me any installation folder. after installing it lokaly directly on the machine everything is installed. . so this issue is solved

**Comment by Distil62** [comment]
Same issue. Where duo manager is installed on your machine ?
