### ISSUE TITLE
Moonlight connected gamepads not being recognized at all.

### ISSUE THREAD

**Issue by laurorual** [DuoStream/Duo#2]
Hello!

I'm currently using Duo on my PC with Moonlight on my FireTV Stick, but if i connect my gamepad directly to my FireTV Stick, it doesn't get recognized/connected by my PC, not on my "main PC" nor on the "PC in my FireTV Stick".
In order for my gamepad to work i have to connect it directly to my PC, but it isn't ideal in my situation. I tried enabling and disabling the "Replace native support for Xbox gamepad" option in Moonlight but nothing happened.
When i connect Moonlight directly to my PC using GameStream, my gamepad works fine while connected directly on my FireTV Stick, so it's definetly something with Duo.
Is there something i'm missing here? 

Also, i didn't understand how the "segregate gamepads" feature works. When i enable it, i can see the 4 emulated gamepads in Ryujinx (Nintendo Switch emulator), but when i try to setup the buttons, none of the 4 gamepads works when pressing the buttons on my gamepad. Do i have to setup something additional to link my gamepad to one of the virtual ones?

Thanks!

**Comment by Black-Seraph** [comment]
The segregation support for gamepads is experimental and certain applications will have trouble working with it, that issue is known already and a given at this point in time.

For those applications you'll have to disable segregation support and install ViGEmBus on your PC to act as a gamepad spawner.

Keep in mind you'll have to restart the Duo service for changes to the segregation setting to take effect.

**Comment by laurorual** [comment]
what about the gamepad not being recognized when connecter to moonlight instead of my PC?

**Comment by laurorual** [comment]
@Black-Seraph don't know why u closed this issue since my main report was about moonlight not recognizing gamepads if connected to the Duo server. Hope you can take a look at this issue at some point!

**Comment by Black-Seraph** [comment]
Please read and follow the instructions I've given you, then report back.

**Comment by laurorual** [comment]
> Please read and follow the instructions I've given you, then report back.

Yeah, installing ViGEmBus seems to help with this issue, only didn't help with the segregation feature.
Hope you can figure this feature out someday!
