### ISSUE TITLE
cant connect to sunshine after restart

### ISSUE THREAD

**Issue by darkjezza** [DuoStream/Duo#21]
cant connect to sunshine after restart

duo version: 1.1.0

![screen shoty](https://github.com/DuoStream/Duo/assets/80877059/9550868d-568f-45ab-be22-a8625b09447c)

**Comment by Orski174** [comment]
Try reinstalling it.

**Comment by darkjezza** [comment]
I figured it out it was name conflicting

**Comment by Black-Seraph** [comment]
I guess we're good to close this issue then.

As a sidenote though: The same issue can happen if you don't keep your RDPWrap patches up to date.

Make sure to check RDP_CnC.exe after every cumulative Windows update and update the rdpwrap.ini in there if needed.
