### ISSUE TITLE
Need help understanding the pricing model

### ISSUE THREAD

**Issue by roseyhead** [DuoStream/Duo#22]
Hoping someone can help me make sense of this. As someone who's not interested in a monthly subscription, it looks like the current version is bought for $20, plus any update in the next month is free, then once the subscription ends any further update costs $20, then you get another month of free updates. Is this accurate?

**Comment by Black-Seraph** [comment]
All of my software, both past and present, including Duo, is accessible via the 10$ tier.

Whatever you download while your subscription is active is yours to keep, but that also means you lose access to the library once the subscription runs out.

However: Duo can be updated with the freely available GitHub builds without losing access to the supporter-only features.
Which means you could just subscribe for a month, pick up the Patreon build and then get all the future updates & bugfixes from the freely available GitHub build from there on out.

To do so, you'd first backup the HKLM:\SOFTWARE\Duo registry key, uninstall the previous Duo version, install the new Duo version and finally restore the registry key.

This is the suggested update procedure regardless of what version of Duo you decide to run, as its the only way to retain instance settings across new revisions.

I hope I was able to answer your question.
