### ISSUE TITLE
Expired password creates constant cpu load

### ISSUE THREAD

**Issue by Gammler** [DuoStream/Duo#25]
Greetings,

today i turned my pc on and had a slugish behaviour while watching YouTube, not knowing what was happening.

In the task manager i found that duo was using constant  ~20%

![image](https://github.com/DuoStream/Duo/assets/7454243/97833587-7ef1-4a72-a200-3fe1cc353699)

After 30 minutes of trying to find out why sunshine was not starting i was thinking of checking the user account and found out that the password expired. I guess it was looping?

I wish duo would be more communicative since debugging wasted a lot time. Maybe also a "Log Tab" in the Manager.

**Comment by Black-Seraph** [comment]
Can confirm the problem and will think about how to best fix this going forward.

For the time being I suggest you just ensure your accounts are set up with password expiration disabled.

**Comment by Black-Seraph** [comment]
Fixed in v1.3.2.
