### ISSUE TITLE
Duo not working after creating a local account

### ISSUE THREAD

**Issue by HJRaptor** [DuoStream/Duo#27]
I have installed Duo on my PC with windows 11 pro. I have created a local account using the provided command however it still gives a " Failed to apply the RdpIdd WUDF driver direct capture patch for hjr " error. 

Thanks,

**Comment by Black-Seraph** [comment]
This usually happens when your AV software eats some of the required files.

I'd first check if RDPWrapper has been installed properly, maybe attach some screenshots of the RDPWrapper & Duo installation directories to get us started.

**Comment by HJRaptor** [comment]
Here is my RDPwrapper directory
![image](https://github.com/DuoStream/Duo/assets/109908618/bc7fe62b-282b-4b19-8a41-12e826cf515b)
Here is my Duo directory
![image](https://github.com/DuoStream/Duo/assets/109908618/cec0cfb5-18ba-4b00-a20a-be1fe7d0c49f)
I have windows defender real-time protection turned off.
Thanks for responding.

**Comment by Black-Seraph** [comment]
Mind opening and screenshotting RDP_CnC.exe for me?

**Comment by Black-Seraph** [comment]
@HJRaptor The newly released version 1.2.1 implements a plethora of session-startup-related fixes.
Please let me know if this fixes your issue or if you need further assistance.
