### ISSUE TITLE
multi gpu setup?

### ISSUE THREAD

**Issue by darkjezza** [DuoStream/Duo#29]
so im currently running multiple GPUs is it possible to use one for the host and one for the client

i tried changing the Adapter Name but that seems to crash sunshine
i also tried changing the Output Name to the display but same thing.

im starting to think is this even possible?

**Comment by Black-Seraph** [comment]
You don't need to segregate anything like that.

You just tell the game in question which GPU to use.

Every Duo instance has access to ALL GPUs.
