### ISSUE TITLE
Can't connect to sunshine

### ISSUE THREAD

**Issue by basofi12** [DuoStream/Duo#3]
This site can’t be reached127.0.0.1 refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall]

ERR_CONNECTION_REFUSED

windows defender and windows firewall already turned off, but still can't connect

**Comment by Black-Seraph** [comment]
Duo logs error messages into the application event log.
Please copy & paste those in here, I can't really help you without those.

**Comment by HardBoiledEggMan** [comment]
I have the same issue and I get different errors for different clients:
- We timed out waiting for the *username1* instance of sunshine.exe
- Failed to apply the RdpIdd WUDF driver direct capture patch for *username2*

**Comment by basofi12** [comment]
where i can find the log file?

**Comment by Black-Seraph** [comment]
> where i can find the log file?

Like I said before: In the Windows application log.
You can find it in the Windows event viewer.
For Windows 11+ you can just right-click the start menu icon and you'll find it there.

**Comment by basofi12** [comment]
Level	Date and Time	Source	Event ID	Task Category
Error	10/31/2023 11:01:21 AM	Duo	1	None	Failed to apply the RdpIdd WUDF driver direct capture patch for ArraChia
Error	10/31/2023 11:00:41 AM	Duo	1	None	Failed to apply the RdpIdd WUDF driver direct capture patch for ArraChia
Error	10/30/2023 10:38:31 AM	Duo	1	None	Failed to apply the RdpIdd WUDF driver direct capture patch for ArraChia

**Comment by Black-Seraph** [comment]
Direct capture errors pop up when the user can't be logged in.

- which version of Duo are you running?
- does the user have a password assigned?
- is the user a newly created local account like the known issues section suggest?

**Comment by basofi12** [comment]
I download the latest duo
Yes, my user has password, should i remove it?
I have only 1 user in my laptop

**Comment by Black-Seraph** [comment]
And you never linked a Microsoft account on your PC?

**Comment by Black-Seraph** [comment]
Then that's the cause of your issue.
Duo requires a unlinked local user account to function properly.

This is known and documented in the README.
