### ISSUE TITLE
Duo failing with "Failed to apply the display driver patch" error

### ISSUE THREAD

**Issue by extermistmonk** [DuoStream/Duo#30]
I have an issue similar to #27 where Duo doesn't start with "Failed to apply the display driver patch", using the latest version (1.2.1). 

Here's the info that was asked for in the previous thread:

![explorer_2024-01-29_13-07-01](https://github.com/DuoStream/Duo/assets/516916/a8d52966-9226-428b-a8c6-d3e907b4a63f)

![explorer_2024-01-29_13-08-14](https://github.com/DuoStream/Duo/assets/516916/910f6f56-cadd-42d6-91dc-b917efa041d9)

![image](https://github.com/DuoStream/Duo/assets/516916/0881de11-a781-41a1-9917-91767cbdb4a3)

I also have Windows Defender turned off, and I created a fresh local account

Thanks

**Comment by Black-Seraph** [comment]
Turn **Network Level Authentication** on.

**Comment by HJRaptor** [comment]
That has fixed the issue. Thanks a lot for helping me troubleshoot this problem!

**Comment by Black-Seraph** [comment]
No problem.
