### ISSUE TITLE
Duo 1.2.5.0 Only Allows One User to be Signed in at a Time

### ISSUE THREAD

**Issue by Orski174** [DuoStream/Duo#34]
As shown in the title, while duo is running only one user can be active at a time.

And any attempt to switch users will log out of the previously logged in user, once Duo is stopped this behavior stops.

Edit: I just noticed the 1.2.6.0 is released so I'm going to test it. This behavior follows in 1.2.6

**Comment by Black-Seraph** [comment]
Duo doesn't do the session management, RDC does, which means that either your RDPWrap termsrv.dll patches are out of date (did you do any big Windows Updates as of late?) or RDPWrap isn't installed properly.

Execute RDP_CnC.exe from the RDPWrapper installation directory and attach a screenshot.
