### ISSUE TITLE
Duo Profile Toggles

### ISSUE THREAD

**Issue by Gammler** [DuoStream/Duo#36]
Hello,

i again noticed this missing feature yesterday when i was hopping a lot between my configured profiles in Duo.

Please implement the possiblity to individually check or uncheck configured Streaming Profiles.

Maybe also with the possiblity to have them automatically reenabled when Duo restarts completely(disable until PC reboot) AND/OR keep them disabled forever until manually reenabled.

I configured a profile for my brother yesterday to let him play for some time and i noticed that with all those profile it takes a long time to start/restart duo. Also the order in which these sessions start is somehow random, sometimes they even close again and then reappear shortly after and then stay there, when i look into the task manager. Don't know what is happening. Sometimes i am trying some new configuration or do some testing and being able to just enable this single profile would come in handy i guess.

Thank you.

**Comment by Black-Seraph** [comment]
The monitor driver patches are time-sensitive, which means they can (and will) fail.

Duo re-applies them as often as is needed, restarting the virtual monitor driver in case of failure, until the patch sticks and initializes properly.

This is why instance start time can either be instantaneous (if the patch works first try) or take up to 2 minutes (in a worst case scenario where the driver has to be restarted 4-5 times).

This is why early versions of Duo had such a high failure rate on boot as there was no driver patch failure-case handling back then.

**Comment by Black-Seraph** [comment]
Version 1.2.8 implements this.
Issue closed.
