### ISSUE TITLE
Hide Duo Profile account password

### ISSUE THREAD

**Issue by Gammler** [DuoStream/Duo#37]
Hello,

just a minor little request, no priority here.

Hide the password shown in Duo Manager. Maybe make the password optionallly visible.

Maybe like this:
![image](https://github.com/DuoStream/Duo/assets/7454243/e72f8705-014e-4e80-a38b-3625fe606beb)

**Comment by Black-Seraph** [comment]
Version 1.2.8 takes care of this.
Issue closed.
