### ISSUE TITLE
"Sunshine" button leads to an unreachable 127.0.0.1 url

### ISSUE THREAD

**Issue by NilouArmpits** [DuoStream/Duo#38]
Basically what the title says, I'm using Windows 11

**Comment by Black-Seraph** [comment]
This just means your instance hasn't been started.

Start your instance first by starting the Duo service.

**Comment by NilouArmpits** [comment]
> This just means your instance hasn't been started.
> 
> Start your instance first by starting the Duo service.

It actually turns out I had to create a new user profile on Windows and have Duo use it on the settings
