### ISSUE TITLE
Add "Online" indicator when session is live

### ISSUE THREAD

**Issue by gattostivalato** [DuoStream/Duo#40]
Very minor thing, but could we add an online indicator to each session to show when it's ready be accessed from Moonlight? Notably it should only show as online when the driver patch is applied successfully. 
Please see attached mock up. Thanks!

<img width="700" alt="Screenshot 2024-02-10 at 22 28 26" src="https://github.com/DuoStream/Duo/assets/126280868/e40fe378-c869-4e61-ab07-cfdef1326562">

**Comment by Black-Seraph** [comment]
The UI will get a bunch of overhauls over the next few versions, but not before #35 and #39 is dealt with.

**Comment by Black-Seraph** [comment]
Implemented as of version 1.3.4.

The web admin panel button now doubles as a online indicator, and can only be clicked once the instance is online.

Issue closed.
