### ISSUE TITLE
Skip Windows Lock Screen in sessions when waking up PC

### ISSUE THREAD

**Issue by gattostivalato** [DuoStream/Duo#41]
When waking up host from sleep and connecting to a session, you’re presented with the windows Lock Screen where you have to enter the password to unlock it.

Since Duo makes a first login automatically when launching the service (there’s no lockscreen when connecting for the first time), is it possible to keep that behaviour when waking up the host?

thanks!

**Comment by Black-Seraph** [comment]
Not possible without first programming a custom Windows logon provider which is **way** beyond the scope of this project.

**Comment by Gammler** [comment]
The only solution is to enable skip password function in windows. @gattostivalato 

https://www.ionos.com/digitalguide/server/configuration/windows-10-automatic-login/
