### ISSUE TITLE
Sunshine web admin fails to start

### ISSUE THREAD

**Issue by jfernandez** [DuoStream/Duo#44]
I recently became a Patron and I'm running into some issues.

Duo starts and the Sunshine Moonlight port appears active since my Steam Deck detects the server and I can request a PIN, but the web UI doesn't load.

I found the Duo logs in the Windows Event Viewer. When I stop and start Duo, I see the following:
- Stopped Gaming
- PATCH: Disabled hardware cursor support
- Started Gaming: https://127.0.0.1:18892 under session 4

But the web admin is still doesn't work and there are no logs that indicate an issue.

**Comment by jfernandez** [comment]
I tracked this down to an issue with having my own copy of Sunshine installed. It appears like the port configs were leaking over. I uninstalled my copy of Sunshine, restart my PC, and the issue went away.

Additionally, I needed to uninstall my virtual display driver as well. This was causing some games to have display issues.

**Comment by Black-Seraph** [comment]
Only just saw your issue but glad to see it was just an issue with a leftover Sunshine install.

Given how your issue is solved, I'll be closing this one now.
