### ISSUE TITLE
HDR disabled in Helldivers 2

### ISSUE THREAD

**Issue by jfernandez** [DuoStream/Duo#45]
HDR is working fine for games like Cyberpunk 2099. But for Helldivers 2, the HDR option in the game settings is greyed out. HDR is enabled on the stream, as verified by the Moonlights stats overlay and the Steam Deck brightness settings (HDR badge is on).

**Comment by Black-Seraph** [comment]
The monitor has HDR enabled, that's where Duo's reach ends.

There really isn't much it can do if a game plays hard-to-get.

One can use third party software like Special-K to force enable it in games though.
