### ISSUE TITLE
Running multiple instances of steam

### ISSUE THREAD

**Issue by StijnWolf** [DuoStream/Duo#48]
After fiddling around with sandboxie specifically for steam, I found it rather annoying and unreliable. [Sandboxie has documentation for steam regarding known conflicts](https://sandboxie-plus.com/sandboxie/knownconflicts/). This isn't really surprising given how many games exist. I tested various games such as Forza Horizon 5, Borderlands 3 and CS2 with steam running in sandboxie and found isolating steam this way very inconsistent. Borderlands 3 worked fine, Forza Horizon 5 didn't launch and CS2 gave me a VAC error when trying to queue for a match. 
Suggesting sandboxie doesn't seem appropriate for steam. It could maybe still be used for other launchers but I mainly use Steam personally.

However, I came across [this post](https://superuser.com/questions/1672615/without-sandboxie-is-there-a-way-to-run-multiple-copies-of-steam) and running multiple instances of steam seems surprisingly easy. I suggest you update your tips and tricks so users can use this trick instead. I've tested this with two users (the host pc user and my steam deck via duo) running separate steam clients using the command in the post. With the same steam account only one account can be online at a time, but you can still launch games from both clients. With two different steam accounts it seems to be working normally. 

Initially, I simply made a .bat file like the answer from SunSpirit suggests which boils down to this command being executed:
`start "Steam_<windows_username>" "C:\Program Files (x86)\Steam\steam.exe" -master_ipc_name_override steam_<windows_username>`. After some trial and error, launching steam with ` -master_ipc_name_override steam_<something_unique>` seems to do the trick. 

This trick also works from a shortcut. I've personally edited the shortcut in the startup menu for all users. 
To launch steam at startup users would need to create a scheduled task instead of letting steam start by itself on user login.  

Could you please test this for yourself and update the documentation if deemed necessary?

**Comment by Black-Seraph** [comment]
I will give this a test as soon as possible and will update the documentation accordingly, should I find that it works as intended that is.
