### ISSUE TITLE
Having Steam open on duo and pc

### ISSUE THREAD

**Issue by zinngar** [DuoStream/Duo#5]
can seem to have both open at the same time? not sure if steam issue??

**Comment by zinngar** [comment]
forgot to mention they are two different accounts

**Comment by Black-Seraph** [comment]
This is known and can be worked around using Sandboxie-Plus.

Just create a sandbox for every Steam account, add steam.exe to the list of sandboxed applications and start it from there, you'll then be able to run multiple instances of Steam side-by-side.

Please read the README first next time before opening issues, this use-case is listed as an example there.
