### ISSUE TITLE
Should overclocking apps run on the virtual session?

### ISSUE THREAD

**Issue by jfernandez** [DuoStream/Duo#52]
I run the Duo Service on my primary Microsoft account profile. I also run MSI Afterburner, RivaTurner, and FanControl to apply my overclock settings.

I created a new local account for the Duo session as instructed by the README. But what is unclear is whether this account should also be running Afterburner, RivaTurner, and FanControl. It currently doesn't. Will my overclock and fan settings be applied to the Duo session if they are not running?

I'd appreciate some guidance on the ideal setup for this.

**Comment by Black-Seraph** [comment]
There's no need to run overclock applications in multiple sessions.
Their settings are applied system-wide and, as such, will affect the whole system, spanning across sessions.
