### ISSUE TITLE
Add warning about expired password for local user

### ISSUE THREAD

**Issue by laurorual** [DuoStream/Duo#53]
I just had an issue with Duo cuz my local user's password expired, and apparently that's what happens by default for new local users in Windows (and i didn't know that).
It would be nice to add a warning about it in Duo, like saying it can't start the instance cuz the password is wrong or expired, or add in the github's readme somethig about disabling the password expiring feature for local users so it won't be a problem in the future.

**Comment by Black-Seraph** [comment]
The README's suggested way of creating accounts quite literally disables expired passwords.

**Comment by laurorual** [comment]
> The README's suggested way of creating accounts quite literally disables expired passwords.

I created the local user using the method suggested in the readme and I still had the password expired.
