### ISSUE TITLE
Duo 1.3.3 and Multiple Steam Instances

### ISSUE THREAD

**Issue by gattostivalato** [DuoStream/Duo#55]
I noticed in the changelog for ver 1.3.3 (or 1.3.2) that Duo can spawn multiple Steam instances, however if Host's Steam is open and I try to launch Steam on Session A, Host's Steam quits by itself. 

Is there any specific workflow to get these to work without Sandboxie? 

Thanks!

**Comment by Black-Seraph** [comment]
Steam has a built-in multi-instance mode that can be enabled via a combination of environment variables and start parameters, see #48 for more information.

Duo 1.3.3 and newer will populate the Sunshine application list of new instances with the right Steam Big Picture shortcuts to make use of this mode, allowing users to run a separate Steam instance on every Duo instance.

If you're an upgrading user, please take a look at the assets/apps.json file and manually carry over the new Steam Big Picture shortcut into your existing instance's apps.json file, located in the config subfolder.

Duo can't upgrade existing instance apps.json files automatically, as these could have been customized by users already, and we wouldn't want to overwrite user-made changes as part of an automatic update.

**Comment by Black-Seraph** [comment]
Please let me know if this solved your issue or if there's anything else you'd like to add, so I can close this issue.

**Comment by gattostivalato** [comment]
Looks good to close, thanks!

**Comment by Black-Seraph** [comment]
Glad to hear all is working well now.

Issue closed.
