### ISSUE TITLE
Scaling in RDP Session

### ISSUE THREAD

**Issue by Mortesh** [DuoStream/Duo#58]
Hi there,

I recently discovered your tool a few days back (Patreon Version 1.34), and it really solved my problem of setting up a gaming server, so thank you! However, I'm encountering an issue with upscaling. The desktop appears to be more upscaled and games like Elden Ring aren't displaying correctly (I guess it has something to do with the RDP Session but I don't know the cause). I've also attached  pictures for reference.
 Could you please advise on how to fix this or identify the origin of the problem? 

Thanks in advance

![grafik](https://github.com/DuoStream/Duo/assets/161311371/27d7b3ad-5385-440b-864d-9bc9bb9099a4)
![grafik](https://github.com/DuoStream/Duo/assets/161311371/ea1217e1-6698-4192-a112-92ebc6c2e3c6)

**Comment by Black-Seraph** [comment]
What are your Moonlight resolution settings?

**Comment by Mortesh** [comment]
Hi there,

my Moonlight resolution settings are the same as my client device: 
![grafik](https://github.com/DuoStream/Duo/assets/161311371/d3b938db-d551-4495-b9e3-24f822036432)

The host System is Windows 10 22H2

**Comment by Black-Seraph** [comment]
I figure you already did [this](https://github.com/DuoStream/Duo/wiki/Troubleshooting#my-instances-display-doesnt-match-my-moonlight-settings)?

Any chance to see your Elden Ring graphical settings?

**Comment by Black-Seraph** [comment]
Glad to hear that changing to borderless windowed did the job.

Issue closed.
