### ISSUE TITLE
DS4windows Controls Host Instead of Client

### ISSUE THREAD

**Issue by Orski174** [DuoStream/Duo#6]
Before using duo I used to use VirtualHere to expose my firestick USB hub to my computer, then use my ds4 after and connect it to my PC as if it's directly connected using USB. Duo is working great, multiple streams each with its own input and output but once I fire up ds4windows and connect my controller, it works just not on my stream. My stream receives absolutely no input other than windows gamebar, which for some reason doesn't work on a normal sunshine stream but works in duo, as for my host it receives all the input. I tried enabling game pad segregation option in duo but noticed no change.

I guess the problem here is that USB ports are Host exclusive, so I probably have to find a way to make it user exclusive?

If you have any ideas that would be great.

Thank you!

**Comment by Orski174** [comment]
I believe this could be fixed by USB redirection to the rdp session, but having this not your usual rdp session using RemoteFX doesn't work.

If you have some insights on how to make it work it would be greatly appreciated.

Thank you!

**Comment by Black-Seraph** [comment]
This is one of the biggest known issues with Duo at this point: Shared hardware.

Everything that is physically (or virtually) connected to a USB hub on the physical system is, technically, available on all sessions, including the physical one.

The gamepad segregation patch works around this to an extend, but isn't a cure-all for the problem.

Future builds will implement a solution based on a fork of HidHide that will allow per-session device jailing which should solve this problem.

**Comment by Orski174** [comment]
That's what I was trying to do, but I don't have any knowledge in rdp sessions and how Duo implements them.

I did open a support ticket on HidHide's Discord server but no one paid it any attention.

With the future builds in mind, how will Duo know what port or device to jail to each and which session if it's connected to the physical system (physically or virtually).

Thank you for your hard work! It really is an amazing project.

**Comment by Black-Seraph** [comment]
My plan is to go by device type.
There are certain characteristics that all gamepad devices share.

I essentially want to rewrite HidHide to do the following:
* Hide all gamepad type input devices except...
* Those that have been spawned by the current session's Sunshine instance...
* And those that the user actively WANTS TO be visible in the current instance

This should ideally allow for a mix of both virtual & physical gamepads, and give control of what to pass through to the user as part of an extended input menu in Duo Manager.

**Comment by Black-Seraph** [comment]
Bad news: The 1609 single-sign driver registry keys no longer work on Windows 11 22H3 Preview (aka. September Cumulative Update for 22H2).

This means I'm more or less cut off from signing the required custom drivers as I don't have access to Microsoft's Hardware Compatibility Dashboard.

This in turn puts a hold on this idea until I can think of a different way to do this or until someone that has access to said dashboard is willing to get in touch and help in signing these drivers.

**Comment by Orski174** [comment]
Sad, why does Microsoft like to limit individual devs work behind quite a big paywall.

Well I guess you can try it out with test signing in the meantime, hopefully someone with a license will offer to help.

Great thanks!

**Comment by Black-Seraph** [comment]
Test signing works but requires Secure Boot to be disabled, which is enough to disqualify it as a potential solution.

I'll have to sleep on this and see if I can find another way, but things are looking grim for a kernel driver based implementation.

The current userspace-based implementation seems to be the best we can do with the limited options we're being presented with.

**Comment by Black-Seraph** [comment]
I've built a fork of the HidHide driver that allows setting per-session filters which essentially allows use to jail virtual ViGEmBus and physical devices into Duo instances / WTS sessions.

Now we only need a Microsoft Partner to double-sign this driver for us and we can have perfect segregated gamepad support and everything that comes with that (like vibration & LED support).

So... anyone out there know somebody that knows somebody that could help us get this driver signed?

**Comment by Orski174** [comment]
Should we ask Nefarius Software?

Put a request on their discord server?

**Comment by Black-Seraph** [comment]
> Should we ask Nefarius Software?
> 
> Put a request on their discord server?

Ideally I'd like to just put a pull-request out and let Nefarius integrate the change into his project, but the repository doesn't accept pull-requests so my hands are tied there.

A real shame too because the change doesn't break existing functionality, which means it could be merged in with the click of a button and just become part of the regular HidHide version.

**Comment by Orski174** [comment]
Should I ask about the possibility to merge it?

**Comment by Black-Seraph** [comment]
> Should I ask about the possibility to merge it?

I just let them know on the Discord about the change, maybe we can get this merged in at some point and / or a few revisions of the code if necessary.

**Comment by Black-Seraph** [comment]
[And merged.](https://github.com/nefarius/HidHide/pull/125)
It will land with the next official release of HidHide, at which point I'll be implementing the glue-code required to put it all together.

**Comment by Orski174** [comment]
Amazing! Thank you for your hard work!

**Comment by Orski174** [comment]
Thank you so much @Black-Seraph!

Great work! I will be trying it now

**Comment by Orski174** [comment]
I think I should connect to the api right?

I'm not really sure how, can't it be done using the HidHideCLI?

**Comment by Black-Seraph** [comment]
> I think I should connect to the api right?
> 
> I'm not really sure how, can't it be done using the HidHideCLI?

Yes.

HidHideCLI.exe --dev-hide "YourDeviceInstancePath!YourDuoSessionId"

That will jail the device to the session.

**Comment by Black-Seraph** [comment]
I might just add some code to automatically jail physical devices to the WTSConsoleSession.

I figure that is what most people would want, as that would mean physical devices are bound to the physical monitor session while virtual devices would be bound to the session that spawned them.

**Comment by Orski174** [comment]
That would be great, I was going to write a script to automate it. 

For some reason even though I jailed the DS4 adapter the virtual Xbox controller and DS4 controller sometimes input leaks to the host (Physical monitor session).

**Comment by Black-Seraph** [comment]
I doubt there's a 100% guaranteed way to jail all possible combinations properly, given how many gamepad translation tools exist out there.

As such I'll just implement what I'd consider the most likely scenario that 90% of all users would encounter.

Physical devices go in the physical session, virtual ones in the virtual sessions that spawned them.

Scenarios outside that will result in undefined behavior and simply are beyond the scope of what I can possibly support.
