### ISSUE TITLE
Custom display scaling not working

### ISSUE THREAD

**Issue by samkitty** [DuoStream/Duo#60]
The custom scaling setting (DPI) doesn't seem to do anything on my DUO session. Using a 1080p 7" handheld (G Cloud) the default 100% is awfully small. I tried editing registry keys LogPixels and Win8DPIScaling manually but that didn't work either.

I realize this is a duplicate of #15 but that one is resolved.

**RdpIdd.dll version 10.0.22621.3085**
**Windows 11 Pro 23H2 OS Build 22631.3155**
**RTX3080**
![20240225_144654](https://github.com/DuoStream/Duo/assets/57629730/3cece26e-6d02-4b08-aa8c-41e651938ba9)

**Comment by XeosCeleres** [comment]
I just wanted to add that the scaling doesn't work on Steam Deck as well. But when you login to the instance account on PC. The scaling is in effect.

**Comment by Black-Seraph** [comment]
Scaling is calculated automatically from the requested stream resolution that Moonlight passes through, with 1280x720 being the 100% baseline before the value is notched to 25% increments.

Ideally we'd want Moonlight to add another Sunshine specific extension to it's protocol, just like they've done in the past to add pen support, that transmits the receiving device's physical screen dimensions.

Doing so would allow us to properly solve this problem, but Moonlight is a completely separate project.

The best we could do on our end is need with the baseline value, make it configurable maybe.

**Comment by samkitty** [comment]
Sweet! Downloading now ᵔ⤙ᵔ
