### ISSUE TITLE
Laggy and Unresponsive UI when Running Playnite in Fullscreen Mode with Duo Gamestreaming Server

### ISSUE THREAD

**Issue by oGobby** [DuoStream/Duo#61]
I'm encountering significant lag and unresponsiveness in the user interface (UI) when running Playnite in fullscreen mode alongside Duo Gamestreaming Server within my local network environment. Specifically, when Playnite is launched and in fullscreen mode, navigating through its UI becomes a cumbersome task, exhibiting delays and sluggishness. However, once games are launched through Playnite, they perform smoothly without any issues.

I'm utilizing a wired connection for both the client and host. I'm using a 78003xd to which I've configured the Game Bar to detect Playnite as a game, but unfortunately, this hasn't alleviated the UI lag issue. refer to this https://github.com/DuoStream/Duo/issues/42 for my reasoning for this decision

This problem seems to be exclusive to the interaction between Duo Server and Playnite, as I do not encounter similar UI performance issues when using Sunshine/moonlight exclusively.

**Comment by Black-Seraph** [comment]
This has to do with dwm.exe and it's power-saving mechanism.

This is the same issue that causes idle desktop lag when capturing frames.

Technically it's not even a Duo, but an overall Windows issue.

I hope to address it with a dwm.exe patch in the future, or some other method to force frame invalidation on the host.

**Comment by Black-Seraph** [comment]
You still with us @oGobby?

**Comment by Black-Seraph** [comment]
Version 1.3.7 just got released, please give that one a try and report back with your results @oGobby.

**Comment by Black-Seraph** [comment]
Closing activity for inactivity.

Some final words on the matter though: I installed Playnite myself just to verify this issue and couldn't reproduce the issue at all.

Playnite's perceived response time was more or less identical to running it in a physical session, which, don't misunderstand me, wasn't great, but Playnite worked equally bad on my physical session as it did in a remote one, as such I'm inclined to believe that this is just Playnite being bad.

Lacking further evidence or feedback this is all I can contribute to the matter at this point in time.
