### ISSUE TITLE
Adding resolution in sunshine breaks instance

### ISSUE THREAD

**Issue by StijnWolf** [DuoStream/Duo#62]
Hey, I've been loving DuoStream for the past month but stumbled upon weird behavior when adding a resolution to sunshine.

I added the following resolutions to sunshine: 1280x800 and 2560x1440. It seems to work fine after applying the settings until you restart Duo. After that, the sunshine instance 'breaks' and reverts to Sunshine's default settings. The instance on my machine normally runs on port 41000, but after this issue it runs on 47990. The instance name reverts to 'Desktop' and I'm sure there's other stuff that gets reverted that I haven't noticed. My Moonlight clients see a different unpaired sunshine instance named 'Desktop'.
 
Steps to reproduce:

- Add a resolution in Sunshine's web UI and apply the settings
- Wait for sunshine to restart and test if it's still running afterwards. The resolution should be applied correctly.
- Restart the instance via Duo Manager
- Sunshine instance reverts to default settings and becomes unavailable for paired Moonlight clients

The easiest fix I found is to delete the entire config folder in the Duo installation folder and reconfigure Duo. This can be quite time consuming and thus rather annoying.

I had sunshine installed prior to using Duo, but uninstalled sunshine normally through windows before installing Duo. I did not manually delete any files so maybe there are some junk sunshine files left on my host.

Please let me know if you can reproduce this behavior and if I should provide more information.

**Comment by Black-Seraph** [comment]
I can confirm your issue and am now looking into the matter, but a quick question:
**Why do you add resolutions manually?**
Duo auto-adjusts the Desktop resolution to match that of the client anyway.

**Comment by StijnWolf** [comment]
I scanned through this video https://youtu.be/tKgDSYueQlE?si=f_3qJvBjqCDaX7JU and around 3:30 he mentioned the sunshine resolution is different from the client resolution. It's supposed to be the 'streaming resolution' akin to the streaming quality of a YouTube video.. atleast that's my understanding from that guy's explanation.

 I have no idea as to how sunshine actually works so took his word for it. I then proceeded to add the aforementioned resolutions.

**Comment by Black-Seraph** [comment]
> I scanned through this video https://youtu.be/tKgDSYueQlE?si=f_3qJvBjqCDaX7JU and around 3:30 he mentioned the sunshine resolution is different from the client resolution. It's supposed to be the 'streaming resolution' akin to the streaming quality of a YouTube video.. atleast that's my understanding from that guy's explanation.
> 
> I have no idea as to how sunshine actually works so took his word for it. I then proceeded to add the aforementioned resolutions.

Yeah, you don't need any of that with Duo.

All of this is done automatically.

Just pick a resolution you'd want to use inside Moonlight and let Duo do its thing, you'll be running at exactly the resolution you picked.

**Comment by XeosCeleres** [comment]
What if you want to use a custom resolution? For example:

1. SteamDeck Moonlight resolution is 1280x800.
2. Now you connect the SteamDeck to a 1080p monitor. You set Moonlight from 800p to 1080p.
3. When you start the remote play, Duo is still 800p.

**Comment by StijnWolf** [comment]
There are other solutions to that problem but that problem is completely on Moonlight's side.

Using MoonDeck is a solution or use my DeckLight script to launch Moonlight.

**Comment by Black-Seraph** [comment]
@XeosCeleres As @StijnWolf already mentioned, you need to make sure that both Moonlight itself **and** the stream settings are set to the correct resolution.

This is a Steam Deck specific caveat, and there really is nothing Duo can do about that.

It's just how the Deck, and its gamescope compositor, work.

**Comment by XeosCeleres** [comment]
@Black-Seraph What do you mean by 'Streaming settings'? I setup Moonlight to 1080p already. But 800p is still displayed on the 1080p External monitor.

**Comment by Black-Seraph** [comment]
> @Black-Seraph What do you mean by 'Streaming settings'? I setup Moonlight to 1080p already. But 800p is still displayed on the 1080p External monitor.

1. Move into Desktop Mode
2. Add Moonlight as a Non-Steam Game on your Deck
3. Return to Game Mode
4. Open the Properties of Moonlight on your Deck UI and change the application's resolution to 1080p
5. Now open Moonlight, go into its settings and change the stream resolution to 1080p

You're now running a 1080p stream with your Deck outputting a 1080p image.

**Comment by Black-Seraph** [comment]
@StijnWolf I'm closing your issue as the newly released version 1.3.7 fixed it.
