### ISSUE TITLE
Stream refresh rate always at max

### ISSUE THREAD

**Issue by zzfuture** [DuoStream/Duo#63]
As the title says, the problem is that sunshine always streams at the max refresh rate of the moonlight session.
This can be compared with the "original" sunshine streaming a youtube video. If the video is at 30 fps and the moonlight session max refresh rate is 60fps, the stream will be at 30 fps because the source is only displaying that amount of frames/s.

With Duo is working different, if the video is 30fps the stream will be maxing the moonlight fps, so stream will be at (ex 60fps, for me is 144fps).

This is for any type of media: games, videos and so on.

Fixing this will be a relive for host and client, because of the dynamic use of the hardware.

**Comment by Black-Seraph** [comment]
No clue where you get that idea from, unless you're running the experimental patch from #61, which does exactly that intentionally to test a theory on lag being caused by encoder underruns.

(Which I've experienced first hand in our test lab, which is why we're testing that patch in the first place.)

**Comment by zzfuture** [comment]
Is Duo v1.3.6, without that patch.
Here a screenshot from my phone, left is sunshine, right duo. Same youtube video, 480p with the purpose of make the source 30fps locked. Duo give always the max of the moonlight session, in this case moonlight in android has 60fps max.


![test](https://github.com/DuoStream/Duo/assets/113058239/4cbca088-acff-44e7-a16f-fb65aadcdef7)

**Comment by Black-Seraph** [comment]
Can you check the FPS on an idle Desktop without animated wallpapers?

On my end 1.3.6 behaves fine and adjusts to the dwm.exe refresh rate.

**Comment by zzfuture** [comment]
With no movement in the background it stays in the 9 fps.
Using windows 11 23H2 Build 22631.3007

![no move](https://github.com/DuoStream/Duo/assets/113058239/659d0bff-30c0-4df3-8a88-b0cb40e73024)

**Comment by Black-Seraph** [comment]
> With no movement in the background it stays in the 9 fps. Using windows 11 23H2 Build 22631.3007 Hardware Used: CPU: 5700x GPU: RX 6700XT (driver 24.2.1 WHQL) RAM: 32GB DDR4
> 
> ![no move](https://private-user-images.githubusercontent.com/113058239/310180892-659d0bff-30c0-4df3-8a88-b0cb40e73024.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTU4NDAsIm5iZiI6MTcwOTY1NTU0MCwicGF0aCI6Ii8xMTMwNTgyMzkvMzEwMTgwODkyLTY1OWQwYmZmLTMwYzAtNGRmMy04YTg4LWIwY2I0MGU3MzAyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxNjE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODYzNzg5MDEzN2FmNTJjOTI0M2RkZTZjZjc4NDkwN2E4NmE3ZTI3MWM0MWZjYTFlZDNiYzE2MjA4NWZjOTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AT3MSDoYRLG0gWYujC8-kvM6mBR_goB_HUZM6nLLdPw)

Then it is working as intended.

Keep in mind that Duo uses a different capture method than regular Sunshine does.

Regular Sunshine captures frames via DXGI screen duplication, while Duo captures its frames directly from a monitor driver and is thus bound to the monitor's refresh rate.

The only frame-related savings that happen at that point are those enforced by the Windows compositor dwm.exe.
