### ISSUE TITLE
Need to restart for Duo to work

### ISSUE THREAD

**Issue by killacam725** [DuoStream/Duo#64]
I have 2 issues:

1) If I logoff a session and try to get back in, I need to restart my computer to be able to connect again on moonlight. There is general inconsistency in being able to connect to an instance

2)Open web admin portal has been greyed out since the first install

I previously had sunshine installed and have already uninstalled it. Am trying to do this on a steam deck.

**Comment by Black-Seraph** [comment]
I can't help you if you don't provide any log files or application event log exports.

The log files can be found in **C:\Program Files\Duo\config**, and the application event log can be accessed through Windows' event viewer, just right click the **Application** log in **Windows Logs** and click on **Save All Events As...** to build a .evtx export file.

**Comment by bavolin** [comment]
I'm having a similar issue. When I sign out and reboot, Sunshine stops working entirely (and the web admin portal is greyed out).

I'm unable to attach the .evtx file. That format is unsupported I guess?

![duo UI](https://github.com/DuoStream/Duo/assets/22353093/d5948f79-e4c1-4687-9d84-b9fc648d3b4d)

[sunshine.log](https://github.com/DuoStream/Duo/files/14516152/sunshine.log)

**Comment by Black-Seraph** [comment]
> EDIT: I think 1.3.7 fixed my issue. It works successfully after reboots and after saving new sunshine resolutions/fps.

Wonderful!

Issue closed then.

**Comment by killacam725** [comment]
I'm still having issues on 1.3.7 but I think it may be because of sunshine? I don't have another instance installed... but seems like I can't get to the WebUI. Am I missing something here? Also how do I attach an event log?

**Comment by killacam725** [comment]
I do see this error:

Faulting application name: sunshine.exe, version: 0.21.0.0, time stamp: 0x65e8901f
Faulting module name: ntdll.dll, version: 10.0.22621.3085, time stamp: 0xbced4b82
Exception code: 0xc0000374
Fault offset: 0x000000000010c7a9
Faulting process id: 0x0x514C
Faulting application start time: 0x0x1DA709E9D889794
Faulting application path: C:\Program Files\Duo\sunshine.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 8bd85d81-8e9d-45e8-b5e2-0a90e03335c6
Faulting package full name: 
Faulting package-relative application ID:

**Comment by killacam725** [comment]
Also this is in my manager.log

3/7/2024 10:30:34 PM [0] AggregateException
One or more errors occurred.
3/7/2024 10:30:34 PM [1] HttpRequestException
An error occurred while sending the request.
3/7/2024 10:30:34 PM [2] WebException
Unable to connect to the remote server
3/7/2024 10:30:34 PM [3] SocketException
No connection could be made because the target machine actively refused it 127.0.0.1:47981

**Comment by killacam725** [comment]
So I just did one more test. Had a fresh uninstall and install of 1.3.7.

Only way that Duo worked was to have 'auto-start' toggled. If this is not toggled, and I try to manually start duo, the entire application does not work. With auto-start toggled, I do have 'open web admin portal' also enabled and can get into sunshine. 

If I stop duo and then start it again - then the entire application does not work including no connectivity to Sunshine. If needed I can create a new issue.

**Comment by killacam725** [comment]
> > EDIT: I think 1.3.7 fixed my issue. It works successfully after reboots and after saving new sunshine resolutions/fps.
> 
> Wonderful!
> 
> Issue closed then.

Unfortunately, my issue still remains although it seems the other user resolved their problem. Can we re-open or should I create a new issue?

**Comment by s1lverkin** [comment]
Same thing for me, I am on 24H2 & 1.5.0 Patreon version, and whenever I am trying to change some stuff on duo manager I need to restart it completely, because when I try to stop the service it just hangs on  Stop_Pending state and not proceeding further.

After killing it with net stop DuoService I can unlock my Duo Manager again, but after that until full PC reboot I am unable to start any instance (clicking start button, but nothing happens)
