### ISSUE TITLE
Maintain public changelog for Duo

### ISSUE THREAD

**Issue by samkitty** [DuoStream/Duo#65]
I am using the Patreon version of Duo but I am no longer subscribed so I can no longer view the Patreon post which contains the changelog. Copying the changes and pasting them here on GitHub would be greatly appreciated because I would love to see what is being worked on/added to Duo.

There is also no way for us to be notified about a new update if I'm not mistaken? Alternatively these can be added to the main **Global Settings** page of the configurator along with the option to update when a new release is available.

**Comment by Black-Seraph** [comment]
Check the GitHub commit history.

The complete changelog is publicly visible there.
