### ISSUE TITLE
Updating Sunshine 

### ISSUE THREAD

**Issue by bavolin** [DuoStream/Duo#66]
What's the process for updating Sunshine? When opening the Web Admin Panel, my instance still says 0.21.0.285368c (and that I'm on the latest version), even though a new build is out.

I was on the nightly version of 0.21 with Duo 1.3.7. I thought I could install Sunshine 0.22 nightly and move the new .exe to the Duo folder to replace the current sunshine.exe. All of the config files when opening the new sunshine web UI point to my original files but I think it messed up my sunshine instance. When I try to run apps from moonlight, they never load on the client (just display the desktop) but if I look at the sunshine host directly, the app opens correctly. I'm probably missing some config connection between the new .exe and my original config files.

**Comment by Black-Seraph** [comment]
The Sunshine version bundled with Duo has been [customized to support shared frame buffer capture](https://github.com/DuoStream/Sunshine).

You can't just replace it with a regular build of Sunshine.

Duo tracks upstream Sunshine and gets updated once a month to stay up to date, which means you can just follow Duo updates and will always be up-to-date by doing so.

**Comment by bavolin** [comment]
Ok great thanks!

And I'm not sure where to ask my 2 other questions. If I should direct them somewhere else in the future, I can!

1. If Duo is on a monthly Sunshine integration update, is it generally the same time each month?

2. If I paid for the Patreon version and need to reinstall Duo on my PC (ex. After a fresh wipe), is there a way to recover my key? And does the same process need to be done for updating Duo versions? I couldn't find anything in the docs related to fresh installs/updates.

**Comment by Black-Seraph** [comment]
1. It's not on a strict schedule as Sunshine updates are squeezed in whenever other projects allow for an opening.
2. Keep whichever version of the Patreon installer you last fetched on hand and use that one to do your initial install. Then switch over to the GitHub builds for updating.
