### ISSUE TITLE
Duo | Does not start at all | V1.3.7

### ISSUE THREAD

**Issue by David-Moreira** [DuoStream/Duo#68]
I have used Duo in the past with success. I haven't used it for sometime however. 

Today, with v1.3.7, I was trying to start it up and nothing.

This is what I have in the instance.log
![image](https://github.com/DuoStream/Duo/assets/22283161/db3ec882-0408-41b9-bac6-7ab73623b5d2)

By opening Task Manager no additional user is logged in. (I have created a local_account user just for duo)
I tried creating another user just to be sure, nothing different happens.

I tried uninstalling & also deleting the config folder completely and installing back again, the error is the same.
Strange that it kept the settings I guess they might be saved on some user folder.

Can you help me troubleshoot? Thank you!

**Comment by David-Moreira** [comment]
> Ran into this a couple days ago, have you tried starting the Sunshine config manually? Go to where you have Duo installed, and run: `sunshine.exe "name of config".conf`
> 
> Check if it can get an adapter, my problem was that Sunshine was running in the background, even though I uninstalled it.

I see. I do have "regular sunshine" installed and I use it when I don't need Duo.
I terminated my "regular sunshine" and tried running "duo sunshine" on my "live user" it is indeed failing to grab the adapter, I have no idea why. It is of note that I did update "regular sunshine" to v0.22.0 no idea if that would make a difference as I would expect the instances configuration to act independently.

![image](https://github.com/DuoStream/Duo/assets/22283161/60188338-9557-4c99-91a2-49deb9b9e49a)


Any Suggestions?

**Comment by HachebeDLC** [comment]
Try downloading the latest portable version of Sunshine and extracting it on the Duo folder, got it crashing again today, and that fixed it.

**Comment by Black-Seraph** [comment]
Duo's Sunshine only works inside of a driver-patched remote session.

Running it standalone on a console session will **never** find an adapter, because there is no suitable adapter present.

Your Instance.log was captured at a bad moment in time, right as Sunshine was starting, so there really isn't any useful output in it.

Try capturing it again and see if you can get more output to display.

Also, export your Application event log inside of Windows' Event Viewer and attach that as well.

Duo logs its driver-related data into the Application event log, while Sunshine logs its data into its own instance-specific log file.

To figure out your issue we need both.

**Comment by David-Moreira** [comment]
I'll reinstall & reboot just to be sure I'm starting from a cleaner slate.
- My instance.log always seems to return that log I posted across runs, I tried several times.
- I looked at the troubleshooting page but nothing seems to apply. Duo did work before. I'm not sure what might have changed in the meantime.

I'll provide the suggested logs in a few after I do a new attempt.

**Comment by David-Moreira** [comment]
Ok so here's my detailed steps
1. Unninstalled Duo 
2. Deleted the Duo folder from C:/Program Files
3. Reboot
4. Installed Duo 3.7.0
5. Reboot
6. Open Duo Manager
7. My previous instance already existed, but deleted and created a new one
8. Created a new instance with my local user account and tried starting up
9. Waited for about 5m, Duo does not seem to be starting up, local user does not show as logged in in the Task Manager.
10. The Security event viewer does display successfully logons for the local user, but it log offs soon after.

I saw a critical error in the System events related to a system driver, I'm not sure what it is, also attached.
**Windows 11 latest**
**CPU:** 12400F
**GPU:** RTX 2060


Here's the requested files:
[DuoTroubleshoot.zip](https://github.com/DuoStream/Duo/files/14603391/DuoTroubleshoot.zip)

**Comment by Black-Seraph** [comment]
> I understand that as users of the app we should be acquainted with these edge cases. But would there be a way you could add some detection that would throw a message like : "It seems like your RDP Wrapper might be out of date, please update it"

Future builds of Duo will incorporate RDPWrapper somewhat more tightly than it currently does, which will take care of this particular edge case by automating it as part of the service start-up.

> I don't know how I missed it... oops. Sorry if I wasted your time.

Don't worry about it. I'm just glad that your issue is now resolved.
