### ISSUE TITLE
Can't set RDP resolution 

### ISSUE THREAD

**Issue by NilouArmpits** [DuoStream/Duo#69]
Exactly what the title says, back then (idk what version) the Duo app had an option on it where you can change the resolution but it seems to have been replaced by "luminosity" and I can't change the resolution even if i already changed the moonlight resolution and "applied" the fixes by logging out the account

Is there still a version where I can use the duo manager to change the resolution?

**Comment by Black-Seraph** [comment]
I figure you must still be running Windows 10?

If so, the easiest way around resolution-based issues is to upgrade the host system to Windows 11 23H2, as that ships with an updated IddCx driver that supports automatic resolution adjustments.

If that isn't an option, mind telling me what resolution you are trying to run the instance at?

A screenshot of the Moonlight settings would go a long way here.

**Comment by Black-Seraph** [comment]
Closed for inactivity.

**Comment by aspar** [comment]
Hello, I've the same problem..
Every time I connect with moonlight I have only low resolution.
I've a win 11 native device
