### ISSUE TITLE
Adding HDR10 support

### ISSUE THREAD

**Issue by Black-Seraph** [DuoStream/Duo#7]
According to the latest 23H2 release notes, IddCx1.10 now supports HDR10 swapchains.

Having looked into the latest RdpIdd driver I also found references to the 0x40 flag, which indicates FP16 (HDR) support.

The RdpIdd driver has two different adapter implementations though, one that is IddCx1.9-based and another that is IddCx1.10-based.

During initialization it reads certain environmental factors and choses one or the other, funny enough, all of my test-rigs end up in the IddCx1.9 path, which means HDR support is out of my reach.

I've yet to identify what environmental factor forces the RdpIdd driver into the IddCx1.10 adapter implementation, but once I figure that one out it should be fairly easy to enable HDR.

**Comment by Black-Seraph** [comment]
First half of this has been implemented in v1.1.1.
There's still more to be done before this will start working properly though.

**Comment by Black-Seraph** [comment]
And the second half has been implemented in v1.2.0 now.
We now have working HDR. Issue closed.

**Comment by OiledGladiator** [comment]
When turning on HDR on Duo I'm getting a very dim screen compared to SDR, is there hidden settings that should be change for it to work properly?
Running on the latest Moonlight build and latest build of Duo.
![20241020_154557](https://github.com/user-attachments/assets/4142d6a9-3926-4119-969d-2803794a063a)
![20241020_154853](https://github.com/user-attachments/assets/99319ab0-b8a7-4c29-afed-4bfa9ed82f39)
