### ISSUE TITLE
Windows reports Duo.exe contains a virus

### ISSUE THREAD

**Issue by sean256** [DuoStream/Duo#70]
This happens on the current github exe build.

![Screenshot 2024-03-17 155739](https://github.com/DuoStream/Duo/assets/6920955/387c501d-9d54-40d8-9a9c-53ff4105deee)

**Comment by Black-Seraph** [comment]
It's a false positive triggered by the fact that Duo patches a handful of libraries in RAM to make multi-seating possible.

See the following point on our known-issues Wiki page for more details: [Antivirus False-Positives](https://github.com/DuoStream/Duo/wiki/Known-Issues#antivirus-false-positives)
