### ISSUE TITLE
Only one session launches, the other one is stuck in a "Started session" loop

### ISSUE THREAD

**Issue by gattostivalato** [DuoStream/Duo#71]
Per title - running 1.3.7, but only session Ciapis launches, while S stays stuck. 

S.txt in Duo\config seems to suggest something is up: 

```
[2024:03:18:14:26:41]: Error: nvprefs: Couldn't open undo file from previous improper termination, or confirm that there's no such file
[2024:03:18:14:26:41]: Info: nvprefs: No need to modify application profile settings
[2024:03:18:14:26:41]: Info: nvprefs: No need to modify global profile settings
[2024:03:18:14:26:41]: Info: Compiling shaders...
[2024:03:18:14:26:41]: Info: System tray created
[2024:03:18:14:26:41]: Info: Compiled shaders
```

<img width="968" alt="Screenshot 2024-03-18 at 14 24 00" src="https://github.com/DuoStream/Duo/assets/126280868/108884f1-8e2f-455e-8a3c-d2a96b93d464">

<img width="1286" alt="Screenshot 2024-03-18 at 14 26 07" src="https://github.com/DuoStream/Duo/assets/126280868/8a1b1096-1da1-4260-acdd-57e3af21ddbf">

**Comment by David-Moreira** [comment]
I've had a similar problem on #68 where basically I just needed to update my RDP Wrapper. I don't know if it's the same problem, but might be worth checking.
![image](https://github.com/DuoStream/Duo/assets/22283161/29d50790-ce61-456b-a4bf-143683c068d3)

**Comment by gattostivalato** [comment]
Thanks, yeah did that as well but no dice. Thanks though!

**Comment by David-Moreira** [comment]
Can't help you then, outside my knowledge. :(
I'd suggest to take a look at #68 and look at the logs/information that the author, @Black-Seraph requested, and get an head start in supplying those to help troubleshoot. I've seen him ask similar logs/info in a few other issues so...

**Comment by Black-Seraph** [comment]
Could you attach a full export of your application event log @gattostivalato?

**Comment by gattostivalato** [comment]
[app-events.zip](https://github.com/DuoStream/Duo/files/14640289/app-events.zip)

here it is, thanks!

**Comment by gattostivalato** [comment]
Thanks! Abroad rn but will be checking this tomorrow hopefully.

**Comment by Black-Seraph** [comment]
When you do find time to check, please make sure you update to the latest build first.

**Comment by gattostivalato** [comment]
Confirmed working on 1.4.0, thanks!
