### ISSUE TITLE
Remote Connection

### ISSUE THREAD

**Issue by godver3** [DuoStream/Duo#72]
I am able to connect to multiple instances on my local network, but unable to connect to the new Duo instance remotely (am still able to connect to the original instance). Any ideas on how to access the Duo instance remotely? Is it possible to connect to multiple instances remotely?

**Comment by Black-Seraph** [comment]
Did you make sure to port-forward the instance's port range properly?

Either by toggling the instance's UPnP option in its corresponding **Web Admin Panel** or manually forwarding the TCP & UDP ports occupied by said instance?

**Comment by godver3** [comment]
I didn’t realize that each instance has its own port range. I’m not sure if that, or enabling UPnP sorted it, but either way it’s working now. Thanks! Please close.
