### ISSUE TITLE
RDPWrapper has been abandoned

### ISSUE THREAD

**Issue by Black-Seraph** [DuoStream/Duo#74]
[See here.](https://github.com/sebaxakerhtc/rdpwrap.ini/issues/366)

Which means we'll have to implement the same functionality in-house to ensure Duo remains compatible with future builds of Windows Home.

The upcoming 24H2 preview build has already been confirmed to **not be compatible** due to the recent abandonment of RDPWrapper, making the re-implementation of RDPWrapper a high priority issue.

No rest for the wicked I guess.

**Comment by loyejaotdiqr47123** [comment]
rdpwrap already supports 24h2.
Look this [https://github.com/loyejaotdiqr47123/rdpwrap](https://github.com/loyejaotdiqr47123/rdpwrap)
Find the way to the offset : [https://blog.csdn.net/weixin_53304770/article/details/136608301](https://blog.csdn.net/weixin_53304770/article/details/136608301)

**Comment by loyejaotdiqr47123** [comment]
> [See here.](https://github.com/sebaxakerhtc/rdpwrap.ini/issues/366)
> 
> Which means we'll have to implement the same functionality in-house to ensure Duo remains compatible with future builds of Windows Home.
> 
> The upcoming 24H2 preview build has already been confirmed to **not be compatible** due to the recent abandonment of RDPWrapper, making the re-implementation of RDPWrapper a high priority issue.
> 
> No rest for the wicked I guess.

 [Edited wrong offset : 26063.1](https://github.com/loyejaotdiqr47123/rdpwrap/commit/8d2a68d1f7774659c00a3651e991a04b11a7e58f)

**Comment by loyejaotdiqr47123** [comment]
> 我知道.
> 
> Build 1.3.8 目前正在进行内部测试，它将更好地集成 RdpWrap，一劳永逸地解决这个问题。

@Black-Seraph [https://github.com/llccd/TermWrap](https://github.com/llccd/TermWrap)
You can take a look at this project, I believe it will be helpful to you

**Comment by maxpereria** [comment]
Friends used the rdp wrapper version of sebaxakerhtc and now I'm wondering how to proceed, if anyone knows of a solution with auto update.
In this case, today one of the computers I have with Windows 10 Pro updated and the RDP Wrapper stopped working. I found a compatible .ini file, but my fear is having to do this process manually every time.
Is anyone using a fork with auto update as well as the sebaxakerhtc version and which is working well?

**Comment by loyejaotdiqr47123** [comment]
> 朋友们使用了 sebaxakerhtc 的 rdp 包装器版本，现在我想知道如何进行，如果有人知道自动更新的解决方案。在这种情况下，今天我拥有的一台装有 Windows 10 Pro 的计算机更新了，RDP 包装器停止工作。我找到了一个兼容的.ini文件，但我担心每次都必须手动执行此过程。是否有人使用具有自动更新功能的分叉以及 sebaxakerhtc 版本，哪个运行良好？

[RDPWrap-v1.8.2.zip](https://github.com/DuoStream/Duo/files/14803313/RDPWrap-v1.8.2.zip)
Added auto update

**Comment by loyejaotdiqr47123** [comment]
> [See here.](https://github.com/sebaxakerhtc/rdpwrap.ini/issues/366)
> 
> Which means we'll have to implement the same functionality in-house to ensure Duo remains compatible with future builds of Windows Home.
> 
> The upcoming 24H2 preview build has already been confirmed to **not be compatible** due to the recent abandonment of RDPWrapper, making the re-implementation of RDPWrapper a high priority issue.
> 
> No rest for the wicked I guess.

For version 10.0.19041.1 and later, I recommend finding the offset of the function CUtils::IsSingleSessionPerUser(int *) , instead of the offset of CSessionArbitrationHelperMgr::IsSingleSessionPerUserEnabled , using the offset of CSessionArbitrationHelperMgr::IsSingleSessionPerUserEnabled , the first logged in user will be kicked out and the sebaxakerhtc find the offset of CSessionArbitrationHelperMgr::IsSingleSessionPerUserEnabled , it will exist kick out the first logged in user issue.

**Comment by SoftwareRat** [comment]
@Black-Seraph patch termsrv.dll yourself
Windows 11: https://www.mysysadmintips.com/windows/clients/998-multiple-rdp-remote-desktop-sessions-in-windows-11
Windows 10: https://www.mysysadmintips.com/windows/clients/998-multiple-rdp-remote-desktop-sessions-in-windows-10

**Comment by loyejaotdiqr47123** [comment]
@Black-Seraph [RDPWrap-1.8.3.zip](https://github.com/DuoStream/Duo/files/14970582/RDPWrap-1.8.3.zip)

**Comment by jorbig** [comment]
> [See here.](https://github.com/sebaxakerhtc/rdpwrap.ini/issues/366)

That post advises to move/convert to the Enterprise multi-session edition of Windows using:
```
slmgr.vbs /ipk CPWHC-NT2C7-VYW78-DHDB2-PG3GK
```

This eliminates the need for RDPWrapper. Isn't this ideal for Duo?

**Comment by loyejaotdiqr47123** [comment]
> [See here.](https://github.com/sebaxakerhtc/rdpwrap.ini/issues/366)
> 
> Which means we'll have to implement the same functionality in-house to ensure Duo remains compatible with future builds of Windows Home.
> 
> The upcoming 24H2 preview build has already been confirmed to **not be compatible** due to the recent abandonment of RDPWrapper, making the re-implementation of RDPWrapper a high priority issue.
> 
> No rest for the wicked I guess.

@Black-Seraph Now it's back.
