### ISSUE TITLE
Moonlight switch resolution issue - used sunshine version

### ISSUE THREAD

**Issue by Ley21** [DuoStream/Duo#75]
Hello,
I found a issue by using the nintendo switch client. With the used sunhine version (0.21.0.xx), I could not connect. I tried it with the latest 0.22.x version and it was working. Is ist possible to update to the latest sunhsin build?
THanks for supprt (moonlight client issue https://github.com/XITRIX/Moonlight-Switch/issues/145)

**Comment by Black-Seraph** [comment]
Will land with build 1.3.8, which is currently in internal testing.
