### ISSUE TITLE
Can't connect via moonlight, and the web button is grayed out

### ISSUE THREAD

**Issue by Mohamed6935** [DuoStream/Duo#76]
Tried with both windows 10 21h2 and 22h2. Neither worked, followed the steps and waited for the feature to install(which didn't show a notification so can't tell if it is a problem or normal)
Can't find the config folder in c:/program files/duo though it does remember my instances after reinstalls. So maybe there are logs but I dunno how to find them
The 22h2 was a vm, didn't have high hopes for moonlight to work through that but still grey web button.
21h2 is main system which I uninstalled sunshine before hand

**Comment by Black-Seraph** [comment]
As with every other issue, I need a copy of the log files (if present, which they don't seem to be in your case) as well as an application event log export before I can provide any help.

**Comment by Mohamed6935** [comment]
Using a new windows to go installation of win 10 22h2 I managed to make it work untill the pin part. No matter how much I restarted it keep on refusing to pair.
Delete pc in moonlight
Get pair code, input it but nothing happens
Then it keep spitting out unexpected end of stream error
![Screenshot_20240330-210142](https://github.com/DuoStream/Duo/assets/103905207/fa4c563f-fcee-456a-9502-ecd76908181e)

**Comment by Black-Seraph** [comment]
That was a known upstream Sunshine issue that was fixed with the recent 1.3.9 release.

Issue closed.
