### ISSUE TITLE
Nvidia driver keep high clock speed when idle with active Duo

### ISSUE THREAD

**Issue by jurifi** [DuoStream/Duo#78]
User created and active with Duo, keep GPU clock high. When I forced down a sunshine from user keep up under Duo (or disable duo) idle gpu clock go down. On main windows profile I have installed sunshine on version v 22.2. and if is it not active streaming idle clock on gpu is low. When start Duo, clock go high. I noticed, when Duo go up, then change in Nvidia driver power profile. This effect draw on my GPU about 50w more :(

I have RTX 3070 with latest Nvidia drivers, on W11 pro.

**Comment by Black-Seraph** [comment]
Duo doesn't touch anything power related, as such I can only guess what might be triggering that profile change of yours.

I guess it might be related in some way to instantiating a nvenc encoder instance?

But without additional data its really difficult to say for sure.

**Comment by jurifi** [comment]
Yes, if streaming is on it is ok. But if is not streaming on, high clock is only with active Duo profile (and sunshine in it no active streaming).  Sunshine solo on host without streaming keep gpu in idle low clock.
