### ISSUE TITLE
Failed to apply the display driver patch in event viewer

### ISSUE THREAD

**Issue by jldkrocks** [DuoStream/Duo#79]
I looked at the troubleshooting and didn't see anything about that error there, what do I need to change?

**Comment by RemixLivee** [comment]
Have you solved it? Can you tell me what you did because I'm having the same problem?

**Comment by ranger149** [comment]
Any update on this?

**Comment by ranger149** [comment]
> Have you solved it? Can you tell me what you did because I'm having the same problem?

Were you able to find a solution?
