### ISSUE TITLE
DS4 ViGEmBus Gamepads don't get jailed properly yet

### ISSUE THREAD

**Issue by Black-Seraph** [DuoStream/Duo#8]
This is because their baseContainerDeviceInstancePath is set to an empty string ("").

For these devices we'll have to jail by their deviceInstancePath (ex. "HID\VID_054C&PID_05C4&REV_0100\2&130c1e12&0&0000").

So much to do...

**Comment by Orski174** [comment]
I don't know if you implemented it like this but, my ds4 profile for a virtual ds4 controller doesn't work on my session neither does the physical controller with no translation. Xinput using ds4windows gets jailed and works well.

**Comment by Black-Seraph** [comment]
Duo can't anticipate external virtual controllers or mapping software.

The jailing is there to keep physical devices & virtual devices (linked to Moonlight connected clients) apart.

Everything else is out of scope for this project, at least until I can incorporate a GUI into Duo Manager for manual assignments of devices.

**Comment by Orski174** [comment]
So for now I can't manually assign using HidHideCLI and can only use the virtual one translated by DS4Windows?

**Comment by Black-Seraph** [comment]
You can manipulate the rules in any way you like but you'll be fighting against Duo every time a new device is added and the callbacks are invoked.

For now you could rollback to an earlier version, if you really absolutely need manual control, but I figure we'll just reintroduce the setting in the GUI that enables or disables segregation, enabled being the new default, so that fringe cases like yours could still be doable for those with the required tinkerer background.
