### ISSUE TITLE
Sunshine does not seem to start, button grayed out and error "Failed to apply the display driver patch"

### ISSUE THREAD

**Issue by RemixLivee** [DuoStream/Duo#83]
Yesterday, I launched the Patreon version (1.3.7), thinking that everything would work right the first time, but unfortunately it didn't!

My configuration:

- Windows 11 23H2
- Laptop with Ryzen 7 5800H (CPU + APU) and Geforce RTX 3070.

First problem: RDP Wrapper is not compatible with Windows 11 23H2. So I followed the advice on the project's GitHub and now it's OK.

I unchecked "Memory integrity" and created a secondary local account. Then, I launched Duo Manager and created my first instance, and clicked on the "Play" symbol. No errors in the interface (expect the button always grayed out), but nothing was happening, and Moonlight wasn't detecting anything.

I went to the "C:\Program Files\Duo" folder for the logs, but there was no "config" folder. Then I went to Windows events and I always get "Failed to apply the display driver patch".

If I manually launch sunshine.exe at the root of the Duo folder, I get the error "Failed to locate an adapter".
![2024-03-29 14 13 17](https://github.com/DuoStream/Duo/assets/165335600/f94c07ba-7e80-4029-99c7-1b36a0af2722)

I've allowed everything in my antivirus software (and even tested disabling it, without success). I also tried uninstalling / reinstalling Duo, and that didn't change anything. By the way, I was surprised to find that the previously created instance was still there.

![2024-03-29 10 16 38](https://github.com/DuoStream/Duo/assets/165335600/f78cea66-5fea-42a3-9eba-8307bd067065)
![2024-03-29 10 17 18](https://github.com/DuoStream/Duo/assets/165335600/bf30875d-2ac8-47c2-bac0-83dafd6c9064)
![2024-03-29 10 19 09](https://github.com/DuoStream/Duo/assets/165335600/3c6ee8e4-c0c6-4b63-b794-36910073615f)
[log.txt](https://github.com/DuoStream/Duo/files/14802270/log.txt)

**Comment by sinan-kaplan** [comment]
I have the same problem.

**Comment by Black-Seraph** [comment]
Your log shows this to be a timing issue of sorts.

The RdpWrap.dll & IddCx.dll hooks aren't being set up fast enough.

Could I have the rest of your system specifications?

**Comment by RemixLivee** [comment]
Thanks for replying, sad there's no solution at the moment.

Here is some additional information about my configuration.

![2024-03-30 16 25 07](https://github.com/DuoStream/Duo/assets/165335600/a1510db5-2866-40b6-8dca-4250ccefbad8)

**Comment by Black-Seraph** [comment]
Did you try 1.3.8 yet?

Could you try that real quick, toggle your instance on or enable its auto-start, wait a minute or two, then export your application event log into a evtx file for me?

**Comment by RemixLivee** [comment]
Of course, here's the log. I have another problem using version 1.3.8 (I submitted a ticket about this earlier).

[log.zip](https://github.com/DuoStream/Duo/files/14812815/log.zip)
![2024-03-30 18 40 21](https://github.com/DuoStream/Duo/assets/165335600/7f2dd62f-bffc-4fb3-a01c-e0f7465e947b)

**Comment by Black-Seraph** [comment]
Why did you set your instance port to the same port as the WebUI?

This can't work, simply because the port is already in use by the WebUI.

That is, of course, a separate issue, but still, it needs fixing on your end or there simply is no chance this instance will ever come online.

**Comment by RemixLivee** [comment]
I created the instance on v1.3.7 and the port was auto-generated. I didn't touch this parameter at all.

I've just changed the instance port, but as you say, the problem persists.

**Comment by Black-Seraph** [comment]
@RemixLivee Please give the newly released version 1.3.9 a try.

Same procedure as always. Let it run for a few minutes, and if the issue is still present, export and attach your application event log here.

**Comment by RemixLivee** [comment]
I've just done the test with version 1.3.9. I let it run for 2 minutes. Here's the log file.

[log.zip](https://github.com/DuoStream/Duo/files/14814712/log.zip)

**Comment by Black-Seraph** [comment]
@RemixLivee Issue #67 has been updated with a new test build for you to try and report back.

**Comment by RemixLivee** [comment]
Thank you for your hard work. I've just tested version 1.4.0 (with my antivirus software disabled) and I'm getting new errors, which you'll find in the attached log. The button is still grayed out.

[log.zip](https://github.com/DuoStream/Duo/files/14826241/log.zip)
