### ISSUE TITLE
[v1.3.8] The local RdpWrap.ini is outdated - No fix possible

### ISSUE THREAD

**Issue by RemixLivee** [DuoStream/Duo#84]
With Duo version 1.3.8, I'm having problems with RDP Wrapper (which I understand is now integrated).

I've just run the new version of Duo and the following events systems occurred:
- The local RdpWrap.ini is outdated, attempting to pull update from GitHub
- The GitHub-hosted RdpWrap.ini doesn't support this version of Windows, checking again in 30 minutes
- The service is waiting for a server-sided RdpWrap.ini update

I open the RdpWrap.ini file at the root of the Duo folder and see that my version isn't there (Windows 11 v10.0.22621.3374). I stop Duo, add the offsets manually, restart Duo but my file is overwritten and the same events appear.

EDIT: The RdpWrap.ini file now contains my Windows version, but the event systems still appear. Very strange...

**Comment by Black-Seraph** [comment]
My system runs the exact same Windows 11 build and it works fine?

Could you elaborate on your edit some more?

What message keeps being repeated in the log?

As for RdpWrap.ini updates, those are being pulled from [our GitHub repository](https://github.com/DuoStream/rdpwrap/blob/master/res/rdpwrap.ini) whenever the local file doesn't contain proper patch offsets for the locally installed Windows build.

**Comment by Black-Seraph** [comment]
@RemixLivee Try the following.

1. Stop the Duo service.
2. Download [Duo.zip](https://github.com/DuoStream/Duo/files/14813094/Duo.zip), unpack it and overwrite **C:\Program Files\Duo\Duo.exe** with the included **Duo.exe**.
3. Clear your application event log.
4. Start the Duo service and wait a few minutes.
5. Export the application event log and attach it here.

**Comment by RemixLivee** [comment]
I followed your procedure, left the service running for 5 minutes then exported the log.

[log.zip](https://github.com/DuoStream/Duo/files/14813488/log.zip)

**Comment by RemixLivee** [comment]
I did a few tests and noticed something surprising. My screenshot shows that the Windows version in my cmd is different from the one reported by RDPWrapOffsetFinder (v10.0.22631.3374 / v10.0.22621.3374). Is this normal?

![2024-03-30 23 36 03](https://github.com/DuoStream/Duo/assets/165335600/d38eafb3-f092-44ce-ba59-c88040938e3d)

**Comment by Black-Seraph** [comment]
Looking at your log, your Windows version is actually 10.0.22621.2860, a version for which we indeed don't have a valid set of RdpWrap patches.

We do however have a valid patch set for 10.0.22621.2861, so maybe try copying that one and rename the header to 10.0.22621.2860.

Let me know if that works for you.

**Comment by Barbarezza** [comment]
> You might even be able to just copy paste the 10.0.22621.2861 patches and rename them to 10.0.22621.2860.

Looks like this works. I am too in version 10.0.22621.286 and i had the same problems. However, it looks like that pairing with a device is not succesfull

When i insert the pin in sunshine, nothing happens, and the device on moonlight stay locked. Dont know if its strictly related.

**Comment by Black-Seraph** [comment]
> > You might even be able to just copy paste the 10.0.22621.2861 patches and rename them to 10.0.22621.2860.
> 
> Looks like this works. I am too in version 10.0.22621.2860 and i had the same problems. However, it looks like that pairing with a device is not succesfull
> 
> When i insert the pin in sunshine, nothing happens, and the device on moonlight stay locked. Dont know if its strictly related.

Yeah, this is a upstream Sunshine issue that was only recently introduced, and now fixed again...

I am building 1.3.9 right now to pull those commits in.

**Comment by Black-Seraph** [comment]
Both issues mentioned fixed in version 1.3.9.

Issue closed.

**Comment by loyejaotdiqr47123** [comment]
> 查看您的日志，您的 Windows 版本实际上是 10.0.22621.2860，我们确实没有一组有效的 RdpWrap 补丁。
> 
> 但是，我们确实为 10.0.22621.2861 设置了有效的补丁，因此您可能距离受支持的版本只有几个 Windows 更新。
> 
> 如果您可以在更新之前捕获一组有效的偏移量并在 rdpwrap 存储库中执行拉取请求，那就太棒了。
> 
> 您甚至可以复制粘贴 10.0.22621.2861 补丁并将其重命名为 10.0.22621.2860。
> 
> 数字的跳跃似乎很小，相同的补丁可能仍然有效。

From Microsoft's database, the 10.0.22621.2860 version was not found, please detect the log error

**Comment by loyejaotdiqr47123** [comment]
![image](https://github.com/DuoStream/Duo/assets/102934154/281c62eb-da31-4b6f-9c9a-950b1c66ecf2)
Wait a minute, I'll download the image for testing now

**Comment by RemixLivee** [comment]
I can confirm that this problem has been solved with version 1.3.9. Thank you very much!

**Comment by Black-Seraph** [comment]
@RemixLivee @Barbarezza Could one of you two provide a copy of your C:\Windows\System32\termsrv.dll file?

@loyejaotdiqr47123 has requested a copy to verify our findings here.

We know we are right, but he seems to not be fully convinced yet.

**Comment by RemixLivee** [comment]
Here it is.

[termsrv.zip](https://github.com/DuoStream/Duo/files/14817132/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
> 在这里。
> 
> [termsrv.zip](https://github.com/DuoStream/Duo/files/14817132/termsrv.zip)
@Black-Seraph 
![image](https://github.com/DuoStream/Duo/assets/102934154/e1fa6946-ffcf-4937-aa86-ce4c691cc94a)
Please check the logs error.

**Comment by Black-Seraph** [comment]
Fixed with the upcoming 1.4.0 version.

Turns out that certain language codes return invalid version information when run against termsrv.dll.
