### ISSUE TITLE
Cannot Get Steam or Any other Apps to Autostart on Console Session

### ISSUE THREAD

**Issue by miamilamiw** [DuoStream/Duo#85]
So I have Duo up and working with 1.38 version however on the console session (I have autologin set for my PC,  I am using same Local account for Console session and Sunshine streaming) whenever I set an app like Steam or other launcher app in Start Menu\Programs\StartUp folder it doesn't autolaunch on login.

I'm king of stomped, seems other apps that don't have an interface autostart like Plex etc

**Comment by Black-Seraph** [comment]
Yeah, this is normal.

Steam's multi-session mode doesn't get enabled by default, so if you have Steam set to auto-start using its **normal settings** it will quite literally cannibalize any other currently running Steam session.

If you need to have both the console session and the remote session auto-start Steam properly, you will need to do so by toggling its multi-session flags on both terminal server sessions somehow, either by putting all of these things into a .bat file or some other way.

Please take a look at the apps.json file that is bundled with Duo for the right Steam parameters.
