### ISSUE TITLE
[v1.3.8] The GitHub-hosted RdpWrap.ini doesn't support this version of Windows, checking again in 30 minutes

### ISSUE THREAD

**Issue by MuiPicante** [DuoStream/Duo#86]
"Open Web User Interface" is greyed out. When I look in the event viewer I get the following error:
"The GitHub-hosted RdpWrap.ini doesn't support this version of Windows, checking again in 30 minutes."

I am using the new version 1.3.8

**Comment by Black-Seraph** [comment]
Whats the file version of your C:\Windows\System32\termsrv.dll file?

**Comment by MuiPicante** [comment]
It's 10.2.22621.3374

**Comment by Black-Seraph** [comment]
> It's 10.2.22621.3374

That can't be right. There's no Windows builds out with minor version set to 2 yet.

Maybe you mean 10.0.22621.3374? If so, that one should work just fine.

**Comment by MuiPicante** [comment]
Yeah sorry, I meant 10.0 of course. But you know what's weird? Duo suddenly started working. 
Event log:
"Started Duo: https://127.0.0.1:53648 under session 2"
But that took really long?

**Comment by Black-Seraph** [comment]
> But that took really long?

The update algorithm is dead simple really.

It checks whether RdpWrap.ini has the patches we need, if not, it will download a new one from our repository in the hopes of finding new patches there.

If it doesn't, it knows we haven't gotten around to adding the patches yet... so it waits a rather large 30 minutes before trying again, as its unlikely hammering the repository with update requests will do much good if the first attempt already yielded no new patches.

**Comment by MuiPicante** [comment]
Ok I have just a last problem. I can't pair my devices with the Duo session. As soon as I enter the PIN, nothing happens. Should I open a new issue?
