### ISSUE TITLE
Can't pair with moonlight and sunshine Via the latest verion

### ISSUE THREAD

**Issue by Mohamed6935** [DuoStream/Duo#87]
Same guy from the moonlight and no config problems from last night. I was using the latest version that you mentioned ( downloaded last night) and it still refused to pair, any idea what to do? Sorry if wasting your time
![Screenshot_20240330-210142](https://github.com/DuoStream/Duo/assets/103905207/00178bb3-ce9e-4672-9eb5-6d22c6757ce6)

**Comment by Black-Seraph** [comment]
Try stopping the service, changing the instance port and restarting it.

**Comment by Mohamed6935** [comment]
Changed ports and disabled fire wall but no luck sadly

**Comment by Black-Seraph** [comment]
Just to be on the same page. Version 1.3.9, right?

**Comment by Mohamed6935** [comment]
Yeah it was 1.3.9, i just downloaded it when I set up the windows to go instance. Which is 2 to 3 days ago I think

**Comment by Mohamed6935** [comment]
It was indeed my bad. Probably I downloaded 1.3.8 right before the new one released. Duo is running perfectly fine so far, great job on it and apologies for wasting your time

**Comment by Black-Seraph** [comment]
No problem. Happy to hear the issue is now resolved.
