### ISSUE TITLE
Should physical gamepads get jailed to the WTSConsoleSession by default?

### ISSUE THREAD

**Issue by Black-Seraph** [DuoStream/Duo#9]
We're currently jailing ViGEmBus devices into the sessions that spawned them, but we don't jail physical gamepads at all, which means they bleed across all sessions, both physical and virtual, by default.

The way I see it we have two options:

- Do nothing, which allows die-hard users to manually jail them via HidHideCLI.exe if necessary, giving them the option to assign host-connected gamepads to Duo instances or the physical WTSConsoleSession at will
- Jail physical gamepads to the WTSConsoleSession by default, which would result in a somewhat more normal / beginner friendly default setting where host-connected gamepads will only work on the physical WTSConsoleSession

So, what do we value more?
Ease of use or versatility?

We can't really have both as a mixed form would cause overlap issues between custom and automatic configurations.

**Comment by Orski174** [comment]
I would say automatic by default and can be toggled. 

A new installation of Duo would have gamepad segregation by default and if one wishes, they can disable it and opt to custom block lists using HidHideCLI

**Comment by Black-Seraph** [comment]
> I would say automatic by default and can be toggled.
> 
> A new installation of Duo would have gamepad segregation by default and if one wishes, they can disable it and opt to custom block lists using HidHideCLI

The question is whether anybody will actually do so by hand and if the time necessary to implement this is warranted at this point in time.

To make manual changes like these happen, one would first need to determine the WTS session ID of the current instance, then manually create the HidHide rules that target this session, and of course, adjust them every time Windows changes the session ID.

Without some sophisticated code to manage these changes one will quickly find themselves in deep waters, which means the job of managing these would, most likely, end up, as part of a new watchdog routine inside the Duo service, with an IPC pendant inside Duo Manager to allow users to manage exceptions to the rule.

At that point we're getting **very** close to re-inventing the HidHideClient GUI, and I kind of question whether this is actually in- or out-of-scope for Duo.

I feel something like this is more suited to be implemented in HidHide itself, and Nefarius already said he was working on a fully scriptable rewrite of HidHide a year ago.

Given that I don't know how far along he is with this rewrite I wonder whether it might just be better to not allow manual control for now, go with option number 2, and then re-visit this topic once said HidHide rewrite has been released to the public, because at that point in time we'd have to rework all of this logic anyway.

The fact that I have other projects that need my attention too only adds fuel to the fire, or rather, drastically reduces the time I have on my hands to figure out & program a hybrid solution that would allow both things to peacefully co-exist.

Besides: There's also the topic of who's going to support these users when things eventually go south because of bad configurations...

That's my opinion on the matter at least.
