### ISSUE TITLE
RDP borked, still borked after removal

### ISSUE THREAD

**Issue by MrJackSpade** [DuoStream/Duo#90]
I attempted to install DUO and it pretty much destroyed RDP for me. I then uninstalled DUO and ran a system integrity check/repair, but RDP is still completely borked. I'm hoping to find a solution to this that doesn't involve needing to reinstall the OS

![image](https://github.com/DuoStream/Duo/assets/17441991/edab74eb-5942-4402-b258-b358fd7f1727)

I don't know the exact version but it looks like I downloaded and installed it around February 4th. I know there must still be some lingering modifications since I can still connect multiple user sessions at the same time. 

Obviously I've done the whole update and reboot thing as well as part of this, that didn't work either.

**Comment by loyejaotdiqr47123** [comment]
[RDPWrap-v1.8.2.zip](https://github.com/DuoStream/Duo/files/14865462/RDPWrap-v1.8.2.zip)
Try running uninstall.bat and install.bat

**Comment by Black-Seraph** [comment]
This might be a lingering registry key from a forced service stop.

I'll double tap and add some more clean-up commands into the setup with 1.4.1.

**Comment by MrJackSpade** [comment]
I've run the uninstall.bat for the wrapper followed by another DISM but I haven't tried the reinstall step yet. Is there something else I should be doing in the meantime?

**Comment by Black-Seraph** [comment]
Open regedit.exe and check the ServiceDll value in HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters.

**Comment by MrJackSpade** [comment]
`%SystemRoot%\System32\termsrv.dll`

**Comment by loyejaotdiqr47123** [comment]
> I've run the uninstall.bat for the wrapper followed by another DISM but I haven't tried the reinstall step yet. Is there something else I should be doing in the meantime?
Try running RDPWInst -r

**Comment by Black-Seraph** [comment]
> `%SystemRoot%\System32\termsrv.dll`

That means Duo uninstalled it's RdpWrap.dll properly, as such your issue lies elsewhere.

On that note, there is a currently on-going known RDP issue with certain Windows builds that's being discussed on Reddit that looks awfully similar to your issue though, maybe this is your issue?

Try the following and report back:

1. Download the latest ViVeTool build from [here](https://github.com/thebookisclosed/ViVe/releases)
2. Execute the following ViVeTool command from an administrative cmd.exe: **ViVeTool.exe /disable /id:43960263**
3. Reboot your computer and see if the issue is resolved

**Comment by MrJackSpade** [comment]
I'm going to be away for the weekend so I'll try this stuff when I get back

For some additional context though, this was a completely fresh windows install back in early February. At the time there was no other software installed aside from Sunshine and Duo (and a few games). I had actually completely reformatted the machine with the goal of being a game-streaming platform. The problem started the first time I logged in as the secondary user account and then has persisted since then regardless of what account I log in as.

Its possible its unrelated to Duo, but the "clean" nature of the install definitely narrows it down quite a bit.

In addition, even after removing Duo, I can still have multiple active sessions and that's not something I was able to do before as far as I know. Both two separate user accounts with active sessions at the same time, as well as multiple active sessions for the same user account.

I'm on 11 pro, so I do have the ability to use RDP server natively, but multiple concurrent user sessions should require Enterprise at minimum 

`The standard versions of Windows 11, such as Windows 11 Pro, do not support multiple concurrent Remote Desktop (RDP) sessions. However, Windows 11 Enterprise and Windows 11 Multi-Session operating systems are designed to support multiple remote desktop sessions. `

So I don't have enterprise but I still have enterprise related abilities that were granted by the installer for Duo, that would imply that there must be some lingering changes left over after the removal right? I would assume if the system had been fully returned to its original state, I would have lost the ability to create multiple concurrent RDP sessions

**Comment by Black-Seraph** [comment]
> So I don't have enterprise but I still have enterprise related abilities that were granted by the installer for Duo, that would imply that there must be some lingering changes left over after the removal right?

While that is correct, the change that actually enables this is the **ServiceDll** value I've asked you to look at for me.

Configuring this value to **%Program Files\Duo\RdpWrap.dll** and restarting TermService would enable this function, while configuring it to **%SystemRoot%\System32\termsrv.dll** and restarting TermService would return things to their regular unmodified behavior.

Given the fact that your **ServiceDll** value shows as **%SystemRoot%\System32\termsrv.dll** means that the modifications made by Duo were successfully undone, which means your issue / function-set extension comes from somewhere else.

**Comment by MrJackSpade** [comment]
> > I've run the uninstall.bat for the wrapper followed by another DISM but I haven't tried the reinstall step yet. Is there something else I should be doing in the meantime?
> 
> Try running RDPWInst -r

I just ran this and now I can no longer maintain multiple active user sessions, which is good. I also no longer see any visual corruption, which is a good sign.

I will give it a day or two before closing the issue though just to be 100% sure the issue is resolved. Every once in a while I would have a stretch of time where it would appear to be working before being corrupted again, so I just want to make sure I don't close the issue prematurely.

**Comment by MrJackSpade** [comment]
Well, it turns out the `Try running RDPWInst -r` didn't work. It appeared to for a while, but the problem came back. I tried running `ViVeTool.exe /disable /id:43960263` and that didn't work either. 

It might be important to note though that the ViVeTool command completed almost instantly, where as the suggestion seems to imply there should have been a delay. I'm not sure if that matters or not

**Comment by MrJackSpade** [comment]
I'll give it a bit to see if anyone thinks of anything and then I'll probably just try a reinstall.

It's possible it's not related to duo, and just a major coincidence it started when I installed Duo. Stranger things have happened. For all I know it was sunshine, something related to the local account setup, or some other setup step not directly related to Duo itself.

**Comment by loyejaotdiqr47123** [comment]
@MrJackSpade Can you upload your termsrv.dll?
I'll check to see if it's been replaced.

**Comment by MrJackSpade** [comment]
![termsrv](https://github.com/DuoStream/Duo/assets/17441991/ed075c10-8103-40cb-b6f4-12352e967dc2)

I wasn't sure how to upload it so I just renamed it to jpg

**Comment by MrJackSpade** [comment]
[termsrv.zip](https://github.com/DuoStream/Duo/files/14935056/termsrv.zip)

**Comment by Black-Seraph** [comment]
@MrJackSpade I thought about your issue some more and I'm thinking that your issue could be caused by AVC444.

I think either your server or client doesn't fully support AVC444, and that's why you're running into those graphical issues.
