### ISSUE TITLE
Memory leak? Idle Duo service taking up 4GB of memory

### ISSUE THREAD

**Issue by samkitty** [DuoStream/Duo#92]
Fresh PC reboot, open Duo without starting a Sunshine instance then open task manager and watch the memory usage of the process **Starts Duo instances**. It initially takes 15mb of RAM but adds 0.1mb every ~4 seconds. Left running for several hours the process was taking up over 4gb of memory despite having no instances of Sunshine running. Restarting the process brings it back to 15mb of RAM.

Can you reproduce?

**Comment by David-Moreira** [comment]
Since you mentioned this, I went over to look at it, I think it's been turned on for about a day, also seems to be taking up an unusual amount of ram:
![image](https://github.com/DuoStream/Duo/assets/22283161/cc680350-dda1-4452-b029-45124b3ba296)

**Comment by Black-Seraph** [comment]
I'll look into this.

**Comment by Black-Seraph** [comment]
Fixed as of version 1.4.1.
