### ISSUE TITLE
[Enchancement] Dedicated "Quit stream" button / shortcut

### ISSUE THREAD

**Issue by kopiezzo** [DuoStream/Duo#93]
Is it possible to add a dedicated shortcut for ending the stream? Currently, the shortcut **CTRL+SHIFT+ALT+Q** (or its gamepad equivalent) **pauses** the stream, which then needs to be held on the Moonlight screen and closed. If we had an additional shortcut that ends the stream, for example, we could leave Steam Big Picture mode running and logged in and return to it as needed without waiting for it to restart or just quickly end the stream and forget it.

I'm looking for a way to most seamless quit stream action without using something like PlayniteWatcher (which doesn't work here because it does not want to work with steam multi-session)

**Comment by Black-Seraph** [comment]
If you're entering the stream via the Steam multi-seat shortcut that Duo ships by default then all you have to do is **Exit Steam** via Steam's built-in menu and the stream will self-terminate.

As for shortcuts... those are technically part of the Moonlight project, and thus out-of-scope for Duo.

And while it is possible to implement these, to an extend, by adding input hooks into Duo's Sunshine fork, it really isn't the best place to put it.

Ignoring best-practices for a moment, what exactly would you suggest?

Do you have a specific shortcut or implementation in mind?

**Comment by kopiezzo** [comment]
I would make the pause shortcut (CTRL+SHIFT+ALT+Q) quit the stream instead of pausing it, as I don't really see the benefit of pausing the stream when using Duo.

> If you're entering the stream via the Steam multi-seat shortcut that Duo ships by default then all you have to do is Exit Steam via Steam's built-in menu and the stream will self-terminate.

This is valid, but I was wondering if we could leave Steam Big Picture open at all times on the client account, and just quit and reconnect at will. If not, quit Steam + stream using the quit shortcut.

**Comment by Black-Seraph** [comment]
Your suggestion isn't implementable in Duo's scope and as such I have no choice but to close the issue at this point. 

I highly suggest you open another issue in the moonlight project as that is where this one belongs.

**Comment by samkitty** [comment]
An hacky option could be to create a batch file that kills the Sunshine.exe process then adding that batch file to Steam as a non-Steam game. You can then kill Sunshine by launching the shortcut from within Big Picture mode.
