### ISSUE TITLE
Duo is unable to start an Sunshine instance at all

### ISSUE THREAD

**Issue by SoftwareRat** [DuoStream/Duo#95]
![image](https://github.com/DuoStream/Duo/assets/40393784/b00ea95c-c7b1-4209-9bcb-4ffd49806d20)

- yes I have local admin privileges
- yes duo too

**Comment by SoftwareRat** [comment]
![image](https://github.com/DuoStream/Duo/assets/40393784/9711caf1-1796-4389-8fa2-0fba076af033)
Same with 62201 port

**Comment by Black-Seraph** [comment]
This isn't your first time here @SoftwareRat, you know how it works.

Please make sure to provide an application event log export as well as your instance log files, there is nothing I can do until you provide these.
