### ISSUE TITLE
duo seems to not start at all today?

### ISSUE THREAD

**Issue by darkjezza** [DuoStream/Duo#99]
i get these in event manager
tested newest versions 1.4.0 to 1.4.3 no work

`The GitHub-hosted RdpWrap.ini doesn't support termsrv.dll version 10.0.22621.3447 yet, checking again in 30 minutes`

`The local RdpWrap.ini doesn't contain patches for termsrv.dll version 10.0.22621.3447, attempting to pull update from GitHub`

**Comment by Black-Seraph** [comment]
The termsrv.dll patches are constantly being updated in an attempt to keep up with Windows Updates.

This cat & mouse game we're playing can result in Duo temporarily breaking on Windows Update patch days, but this issue will always end up resolving itself as Duo's rdpwrap repository gets updated.
